/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author DUCNAM
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
      
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension d = t.getScreenSize();
        int h = d.height;
        int w = d.width;
        this.setSize( w , h);
        setExtendedState(MAXIMIZED_BOTH);
        Home home = new Home();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(home).setVisible(true);

    }

    public void setColor(JPanel p) {
        p.setBackground(new Color(255, 255, 102));
    }

    public void resetColor(JPanel p1) {
        p1.setBackground(new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpnHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpnHangHoa = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpnHangTrongKho1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpnHangHoa1 = new javax.swing.JPanel();
        jpngiaodich = new javax.swing.JLabel();
        jpnqlNVien = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpnqlKH = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidepanel.setBackground(new java.awt.Color(0, 153, 255));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone");
        sidepanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 90));

        jpnHome.setBackground(new java.awt.Color(255, 255, 102));
        jpnHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jpnHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpnHomeMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpnHomeMouseMoved(evt);
            }
        });
        jpnHome.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jpnHomeMouseWheelMoved(evt);
            }
        });
        jpnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnHomeMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Home");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home1.png"))); // NOI18N

        javax.swing.GroupLayout jpnHomeLayout = new javax.swing.GroupLayout(jpnHome);
        jpnHome.setLayout(jpnHomeLayout);
        jpnHomeLayout.setHorizontalGroup(
            jpnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHomeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jpnHomeLayout.setVerticalGroup(
            jpnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnHomeLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jpnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        sidepanel.add(jpnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 190, 80));

        jpnHangHoa.setBackground(new java.awt.Color(255, 255, 102));
        jpnHangHoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jpnHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnHangHoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnHangHoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnHangHoaMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Hàng hóa");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/product.png"))); // NOI18N

        javax.swing.GroupLayout jpnHangHoaLayout = new javax.swing.GroupLayout(jpnHangHoa);
        jpnHangHoa.setLayout(jpnHangHoaLayout);
        jpnHangHoaLayout.setHorizontalGroup(
            jpnHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHangHoaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpnHangHoaLayout.setVerticalGroup(
            jpnHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnHangHoaLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jpnHangHoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        sidepanel.add(jpnHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 190, 80));

        jpnHangTrongKho1.setBackground(new java.awt.Color(255, 255, 102));
        jpnHangTrongKho1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jpnHangTrongKho1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnHangTrongKho1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnHangTrongKho1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnHangTrongKho1MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Quản lý cấu hình ");

        javax.swing.GroupLayout jpnHangTrongKho1Layout = new javax.swing.GroupLayout(jpnHangTrongKho1);
        jpnHangTrongKho1.setLayout(jpnHangTrongKho1Layout);
        jpnHangTrongKho1Layout.setHorizontalGroup(
            jpnHangTrongKho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHangTrongKho1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnHangTrongKho1Layout.setVerticalGroup(
            jpnHangTrongKho1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHangTrongKho1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        sidepanel.add(jpnHangTrongKho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 190, 80));

        jpnHangHoa1.setBackground(new java.awt.Color(255, 255, 102));
        jpnHangHoa1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jpnHangHoa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnHangHoa1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnHangHoa1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnHangHoa1MouseExited(evt);
            }
        });

        jpngiaodich.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jpngiaodich.setForeground(new java.awt.Color(51, 51, 51));
        jpngiaodich.setText("Giao dịch");

        javax.swing.GroupLayout jpnHangHoa1Layout = new javax.swing.GroupLayout(jpnHangHoa1);
        jpnHangHoa1.setLayout(jpnHangHoa1Layout);
        jpnHangHoa1Layout.setHorizontalGroup(
            jpnHangHoa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHangHoa1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jpngiaodich)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jpnHangHoa1Layout.setVerticalGroup(
            jpnHangHoa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHangHoa1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jpngiaodich, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        sidepanel.add(jpnHangHoa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 190, 80));

        jpnqlNVien.setBackground(new java.awt.Color(255, 255, 102));
        jpnqlNVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jpnqlNVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnqlNVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnqlNVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnqlNVienMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Nhân viên");

        javax.swing.GroupLayout jpnqlNVienLayout = new javax.swing.GroupLayout(jpnqlNVien);
        jpnqlNVien.setLayout(jpnqlNVienLayout);
        jpnqlNVienLayout.setHorizontalGroup(
            jpnqlNVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnqlNVienLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel10)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jpnqlNVienLayout.setVerticalGroup(
            jpnqlNVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnqlNVienLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        sidepanel.add(jpnqlNVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 190, -1));

        jpnqlKH.setBackground(new java.awt.Color(255, 255, 102));
        jpnqlKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jpnqlKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnqlKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnqlKHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnqlKHMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Khách hàng");

        javax.swing.GroupLayout jpnqlKHLayout = new javax.swing.GroupLayout(jpnqlKH);
        jpnqlKH.setLayout(jpnqlKHLayout);
        jpnqlKHLayout.setHorizontalGroup(
            jpnqlKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnqlKHLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jpnqlKHLayout.setVerticalGroup(
            jpnqlKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnqlKHLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        sidepanel.add(jpnqlKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 190, -1));

        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1800, 1080));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1760, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1760, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 767, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHomeMouseClicked
        Home home = new Home();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(home).setVisible(true);

    }//GEN-LAST:event_jpnHomeMouseClicked

    private void jpnHomeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHomeMouseDragged

    }//GEN-LAST:event_jpnHomeMouseDragged

    private void jpnHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHomeMouseMoved

    }//GEN-LAST:event_jpnHomeMouseMoved

    private void jpnHomeMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jpnHomeMouseWheelMoved

    }//GEN-LAST:event_jpnHomeMouseWheelMoved

    private void jpnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHomeMouseExited
        setColor(jpnHome);
    }//GEN-LAST:event_jpnHomeMouseExited

    private void jpnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHomeMouseEntered
        resetColor(jpnHome);
    }//GEN-LAST:event_jpnHomeMouseEntered

    private void jpnHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangHoaMouseClicked
        // TODO add your handling code here:
//        QuanLyKhoJFrame sp = new QuanLyKhoJFrame();
        QuanLySanPham sp = new QuanLySanPham();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(sp).setVisible(true);
    }//GEN-LAST:event_jpnHangHoaMouseClicked

    private void jpnHangHoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangHoaMouseEntered
        // TODO add your handling code here:
        resetColor(jpnHangHoa);
    }//GEN-LAST:event_jpnHangHoaMouseEntered

    private void jpnHangHoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangHoaMouseExited
        // TODO add your handling code here:
        setColor(jpnHangHoa);
    }//GEN-LAST:event_jpnHangHoaMouseExited

    private void jpnHangTrongKho1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangTrongKho1MouseClicked
        // TODO add your handling code here:
        QuanLyChiTietJFrame sp = new QuanLyChiTietJFrame();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(sp).setVisible(true);
    }//GEN-LAST:event_jpnHangTrongKho1MouseClicked

    private void jpnHangTrongKho1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangTrongKho1MouseEntered
        // TODO add your handling code here:
        resetColor(jpnHangTrongKho1);
    }//GEN-LAST:event_jpnHangTrongKho1MouseEntered

    private void jpnHangTrongKho1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangTrongKho1MouseExited
        // TODO add your handling code here:
        setColor(jpnHangTrongKho1);
    }//GEN-LAST:event_jpnHangTrongKho1MouseExited

    private void jpnHangHoa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangHoa1MouseClicked
        // TODO add your handling code here:
        QuanlyGiaoDichJFrame sp = new QuanlyGiaoDichJFrame();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(sp).setVisible(true);
    }//GEN-LAST:event_jpnHangHoa1MouseClicked

    private void jpnHangHoa1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangHoa1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnHangHoa1MouseEntered

    private void jpnHangHoa1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHangHoa1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnHangHoa1MouseExited

    private void jpnqlNVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnqlNVienMouseClicked
        // TODO add your handling code here:
        QuanlyNhanVienJFrame sp = new QuanlyNhanVienJFrame();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(sp).setVisible(true);
    }//GEN-LAST:event_jpnqlNVienMouseClicked

    private void jpnqlNVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnqlNVienMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnqlNVienMouseEntered

    private void jpnqlNVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnqlNVienMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnqlNVienMouseExited

    private void jpnqlKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnqlKHMouseClicked
         QuanLyKhachHang kh = new QuanLyKhachHang();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(kh).setVisible(true);
    }//GEN-LAST:event_jpnqlKHMouseClicked

    private void jpnqlKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnqlKHMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnqlKHMouseEntered

    private void jpnqlKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnqlKHMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnqlKHMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jpnHangHoa;
    private javax.swing.JPanel jpnHangHoa1;
    private javax.swing.JPanel jpnHangTrongKho1;
    private javax.swing.JPanel jpnHome;
    private javax.swing.JLabel jpngiaodich;
    private javax.swing.JPanel jpnqlKH;
    private javax.swing.JPanel jpnqlNVien;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
