/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.Models.BusDongSpModel;
import BUS.Models.BusHangModel;
import BUS.Services.DongSPService;
import BUS.Services.HangService;
import GUI.Services.IEditService;
import GUI.Services.MessageService;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QLDongSP extends javax.swing.JFrame implements IEditService<BusDongSpModel> {

    /**
     * Creates new form QLDongSP
     */
    int row = -1;
    DongSPService dongSPService = new DongSPService();
    HangService hangService = new HangService();

    public QLDongSP() {
        initComponents();
         getContentPane().setBackground(Color.WHITE);
         desginTable();
        this.init();
    }
public void desginTable() {
        tbldsd.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        tbldsd.getTableHeader().setOpaque(false);
        tbldsd.getTableHeader().setBackground(new Color(25, 29, 74));
        tbldsd.getTableHeader().setForeground(Color.WHITE);
        tblnsd.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        tbldsd.getTableHeader().setDraggedColumn(null);
       tblnsd.getTableHeader().setOpaque(false);
         tblnsd.getTableHeader().setBackground(new Color(25, 29, 74));
         tblnsd.getTableHeader().setForeground(Color.WHITE);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel54 = new javax.swing.JPanel();
        btnThem4 = new javax.swing.JButton();
        btnSua4 = new javax.swing.JButton();
        btnLamMoiForm4 = new javax.swing.JButton();
        rdo0 = new javax.swing.JRadioButton();
        rdo1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenDongsp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TAB = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldsd = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblnsd = new javax.swing.JTable();
        cboHangsp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel54.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnThem4.setBackground(new java.awt.Color(25, 29, 74));
        btnThem4.setForeground(new java.awt.Color(25, 29, 74));
        btnThem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add1.png"))); // NOI18N
        btnThem4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 29, 74), 30));
        btnThem4.setBorderPainted(false);
        btnThem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem4ActionPerformed(evt);
            }
        });
        jPanel54.add(btnThem4);

        btnSua4.setBackground(new java.awt.Color(25, 29, 74));
        btnSua4.setForeground(new java.awt.Color(25, 29, 74));
        btnSua4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        btnSua4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 29, 74), 30));
        btnSua4.setBorderPainted(false);
        btnSua4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua4ActionPerformed(evt);
            }
        });
        jPanel54.add(btnSua4);

        btnLamMoiForm4.setBackground(new java.awt.Color(25, 29, 74));
        btnLamMoiForm4.setForeground(new java.awt.Color(25, 29, 74));
        btnLamMoiForm4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/neww.png"))); // NOI18N
        btnLamMoiForm4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 29, 74), 30));
        btnLamMoiForm4.setBorderPainted(false);
        btnLamMoiForm4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoiForm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiForm4ActionPerformed(evt);
            }
        });
        jPanel54.add(btnLamMoiForm4);

        rdo0.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo0);
        rdo0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdo0.setForeground(new java.awt.Color(25, 29, 74));
        rdo0.setText("Ngừng sử dụng");

        rdo1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo1);
        rdo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdo1.setForeground(new java.awt.Color(25, 29, 74));
        rdo1.setSelected(true);
        rdo1.setText("Đang sử dụng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 29, 74));
        jLabel3.setText("Trạng thái");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 10, 46));
        jLabel2.setText("Hãng sản phẩm");

        txtTenDongsp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTenDongsp.setForeground(new java.awt.Color(25, 29, 74));
        txtTenDongsp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(5, 10, 46)));
        txtTenDongsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDongspActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(5, 10, 46));
        jLabel1.setText("Tên dòng sản phẩm");

        TAB.setBackground(new java.awt.Color(255, 255, 255));
        TAB.setForeground(new java.awt.Color(102, 0, 102));
        TAB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TAB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABMouseClicked(evt);
            }
        });

        tbldsd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbldsd.setForeground(new java.awt.Color(25, 29, 74));
        tbldsd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã dòng sản phẩm", "Tên dòng sản phẩm", "Hãng sản phẩm", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldsd.setGridColor(new java.awt.Color(25, 29, 74));
        tbldsd.setRowHeight(25);
        tbldsd.setRowMargin(0);
        tbldsd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldsdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldsd);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );

        TAB.addTab("Đang sử dụng", jPanel2);

        tblnsd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblnsd.setForeground(new java.awt.Color(25, 29, 74));
        tblnsd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã dòng sản phẩm", "Tên dòng sản phẩm", "Hãng sản phẩm", "Trạng thái"
            }
        ));
        tblnsd.setGridColor(new java.awt.Color(25, 29, 74));
        tblnsd.setRowHeight(25);
        tblnsd.setRowMargin(0);
        tblnsd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblnsdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblnsd);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );

        TAB.addTab("Ngừng sử dụng", jPanel3);

        cboHangsp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboHangsp.setForeground(new java.awt.Color(25, 29, 74));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TAB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboHangsp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(rdo1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDongsp))
                .addGap(34, 34, 34))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(634, Short.MAX_VALUE)
                    .addComponent(rdo0, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(TAB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDongsp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(cboHangsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdo1)
                .addGap(18, 18, 18)
                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(rdo0)
                    .addContainerGap(92, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboHangsp, txtTenDongsp});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSua4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua4ActionPerformed
        // TODO add your handling code here:
        if (TAB.getSelectedIndex() == 0) {
            update();
        } else {
            update2();
        }
    }//GEN-LAST:event_btnSua4ActionPerformed

    private void btnThem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem4ActionPerformed
        insert();        // TODO add your handling code here:
    }//GEN-LAST:event_btnThem4ActionPerformed

    private void btnLamMoiForm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiForm4ActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnLamMoiForm4ActionPerformed

    private void tbldsdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldsdMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.row = tbldsd.getSelectedRow();
            this.edit();

        }
    }//GEN-LAST:event_tbldsdMouseClicked

    private void tblnsdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnsdMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.row = tblnsd.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblnsdMouseClicked

    private void TABMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABMouseClicked
        // TODO add your handling code here:
        if (TAB.getSelectedIndex() == 0) {
            clearForm();
            updateStatus();
        } else {
            clearForm();
            updateStatus2();
        }
    }//GEN-LAST:event_TABMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        QuanLySanPham.fillDongCombo();
    }//GEN-LAST:event_formWindowClosed

    private void txtTenDongspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDongspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDongspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDongSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDongSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDongSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDongSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDongSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TAB;
    private javax.swing.JButton btnLamMoiForm4;
    private javax.swing.JButton btnSua4;
    private javax.swing.JButton btnThem4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboHangsp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdo0;
    private javax.swing.JRadioButton rdo1;
    private javax.swing.JTable tbldsd;
    private javax.swing.JTable tblnsd;
    private javax.swing.JTextField txtTenDongsp;
    // End of variables declaration//GEN-END:variables

    DefaultComboBoxModel<BusHangModel> hangModel;
    List<BusHangModel> listHang = new ArrayList<>();

    @Override
    public void init() {
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.fillTableDsd();
        this.fillTableNsd();
        updateStatus();
        this.row = -1;
        this.fillToCombo();
    }

    void fillTableDsd() {
        DefaultTableModel modelsd = (DefaultTableModel) tbldsd.getModel();
        modelsd.setRowCount(0);
        try {
            List<BusDongSpModel> listdsd = dongSPService.selectAll();
            for (BusDongSpModel x : listdsd) {
                Object[] row = {x.getMaDong(), x.getTenDong(), x.getBusHangModel(),
                    x.isTrangThai() ? "Đang sử dụng" : "Ngừng sử dụng"};
                modelsd.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    void fillTableNsd() {
        DefaultTableModel modelnsd = (DefaultTableModel) tblnsd.getModel();
        modelnsd.setRowCount(0);
        try {
            List<BusDongSpModel> listnsd = dongSPService.selectRecycle();
            if (listnsd != null) {
                for (BusDongSpModel x : listnsd) {
                    Object[] row = {x.getMaDong(), x.getTenDong(), x.getBusHangModel().getTenHang(),
                        x.isTrangThai() ? "Đang sử dụng" : "Ngừng sử dụng"};
                    modelnsd.addRow(row);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void clearForm() {
        BusDongSpModel busCameraModel = new BusDongSpModel();
        this.row = -1;
        this.setForm(busCameraModel);
        this.updateStatus();
    }

    @Override
    public void setForm(BusDongSpModel entity) {
        txtTenDongsp.setText(entity.getTenDong());
        cboHangsp.getModel().setSelectedItem(entity.getBusHangModel());
        if (entity.isTrangThai()) {
            rdo1.setSelected(true);
        } else {
            rdo0.setSelected(true);
        }
    }

    @Override
    public void updateStatus() {
        boolean edit = (this.row >= 0);
        btnThem4.setEnabled(!edit);
        btnSua4.setEnabled(edit);
        btnLamMoiForm4.setEnabled(true);
    }

    public void updateStatus2() {
        boolean edit = (this.row >= 0);
        btnThem4.setEnabled(false);
        btnSua4.setEnabled(edit);
        btnLamMoiForm4.setEnabled(false);
    }

    @Override
    public void insert() {
        BusDongSpModel busDongSpModel = this.getForm();
        try {
            dongSPService.insert(busDongSpModel);
            this.fillTableDsd();
            this.fillTableNsd();
            this.clearForm();
            this.updateStatus();
            MessageService.alert(this, "ok");
        } catch (Exception e) {
            MessageService.alert(this, "err");
            e.printStackTrace();
        }
    }

    @Override
    public void update() {
        BusDongSpModel busCameraModel = this.getForm();
        int idDongsp = (int) tbldsd.getValueAt(this.row, 0);
        busCameraModel.setMaDong(idDongsp);
        try {
            dongSPService.update(busCameraModel);
            this.fillTableDsd();
            this.fillTableNsd();
            MessageService.alert(this, "ok");
        } catch (Exception e) {
            MessageService.alert(this, "err");

        }
    }

    public void update2() {
        BusDongSpModel busCameraModel = this.getForm();
        int idDongsp = (int) tblnsd.getValueAt(this.row, 0);
        busCameraModel.setMaDong(idDongsp);
        try {
            dongSPService.update(busCameraModel);
            this.fillTableNsd();
            this.fillTableDsd();
            MessageService.alert(this, "ok");
        } catch (Exception e) {
            MessageService.alert(this, "err");
            e.printStackTrace();
        }
    }

    @Override
    public void delete() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void edit() {
        if (TAB.getSelectedIndex() == 0) {
            int idDongsp = (int) tbldsd.getValueAt(this.row, 0);
            BusDongSpModel busCameraModel = this.dongSPService.selectByID(idDongsp);
            setForm(busCameraModel);
            updateStatus();
        } else {
            int idDongsp = (int) tblnsd.getValueAt(this.row, 0);
            BusDongSpModel busCameraModel = this.dongSPService.selectByID(idDongsp);
            setForm(busCameraModel);
            updateStatus2();

        }
    }

    public void fillToCombo() {
        hangModel = (DefaultComboBoxModel) cboHangsp.getModel();
        hangModel.removeAllElements();
        try {
            listHang = hangService.selectAll();
            if (listHang != null) {
                for (BusHangModel busHangModel : listHang) {
                    hangModel.addElement(busHangModel);
                }
            }
        } catch (Exception e) {
        }
    }

    @Override
    public void fillTable() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void first() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void last() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void next() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void previous() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean validateForm(boolean isEdit) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public BusDongSpModel getForm() {
        BusDongSpModel busDongSpModel = new BusDongSpModel();
        busDongSpModel.setTenDong(txtTenDongsp.getText());
        busDongSpModel.setBusHangModel((BusHangModel) cboHangsp.getSelectedItem());
        busDongSpModel.setTrangThai(rdo1.isSelected());
        return busDongSpModel;
    }
}
