/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.Models.BusRomModel;
import BUS.Services.RomService;
import GUI.Services.IEditService;
import GUI.Services.MessageService;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QLRom extends javax.swing.JFrame implements IEditService<BusRomModel> {

    /**
     * Creates new form QLRom
     */
    public QLRom() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
         desginTable();
        this.init();
    }
 public void desginTable() {
        tblRom.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        tblRom.getTableHeader().setOpaque(false);
        tblRom.getTableHeader().setBackground(new Color(25, 29, 74));
       tblRom.getTableHeader().setForeground(Color.WHITE);
        
        tblRom.getTableHeader().setDraggedColumn(null);
         tblXoa.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
      tblXoa.getTableHeader().setOpaque(false);
          tblXoa.getTableHeader().setBackground(new Color(25, 29, 74));
          tblXoa.getTableHeader().setForeground(Color.WHITE);
    }
     public void changeColor(JButton hover, Color rand) {
        hover.setBackground(rand);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRom = new javax.swing.JTable();
        jPanel53 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        txtDungLuong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLoaiRam = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblXoa = new javax.swing.JTable();
        btnbackup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(102, 0, 102));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblRom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblRom.setForeground(new java.awt.Color(25, 29, 74));
        tblRom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Rom", "Loại Rom", "Dung Lượng Rom"
            }
        ));
        tblRom.setGridColor(new java.awt.Color(25, 29, 74));
        tblRom.setRowHeight(25);
        tblRom.setRowMargin(0);
        tblRom.getTableHeader().setReorderingAllowed(false);
        tblRom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRom);
        if (tblRom.getColumnModel().getColumnCount() > 0) {
            tblRom.getColumnModel().getColumn(0).setMinWidth(0);
            tblRom.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel53.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnThem.setBackground(new java.awt.Color(25, 29, 74));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add1.png"))); // NOI18N
        btnThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 29, 74), 70));
        btnThem.setBorderPainted(false);
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemMouseExited(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel53.add(btnThem);

        btnSua.setBackground(new java.awt.Color(25, 29, 74));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        btnSua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 29, 74), 70));
        btnSua.setBorderPainted(false);
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaMouseExited(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel53.add(btnSua);

        btnXoa.setBackground(new java.awt.Color(25, 29, 74));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete1.png"))); // NOI18N
        btnXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 29, 74), 70));
        btnXoa.setBorderPainted(false);
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaMouseExited(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel53.add(btnXoa);

        btnLamMoi.setBackground(new java.awt.Color(25, 29, 74));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/neww.png"))); // NOI18N
        btnLamMoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 29, 74), 70));
        btnLamMoi.setBorderPainted(false);
        btnLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseExited(evt);
            }
        });
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        jPanel53.add(btnLamMoi);

        txtDungLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDungLuong.setForeground(new java.awt.Color(25, 29, 74));
        txtDungLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(5, 10, 46)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 10, 46));
        jLabel2.setText("Dung Lượng Rom");

        txtLoaiRam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLoaiRam.setForeground(new java.awt.Color(25, 29, 74));
        txtLoaiRam.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(5, 10, 46)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(5, 10, 46));
        jLabel1.setText("Loại Rom");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(5, 10, 46));
        jLabel4.setText("GB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtLoaiRam, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDungLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoaiRam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDungLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Danh sách", jPanel1);

        tblXoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblXoa.setForeground(new java.awt.Color(25, 29, 74));
        tblXoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Rom", "Loại Rom", "Dung Lượng Rom"
            }
        ));
        tblXoa.setGridColor(new java.awt.Color(25, 29, 74));
        tblXoa.setRowHeight(25);
        tblXoa.setRowMargin(0);
        tblXoa.getTableHeader().setReorderingAllowed(false);
        tblXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblXoaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblXoa);
        if (tblXoa.getColumnModel().getColumnCount() > 0) {
            tblXoa.getColumnModel().getColumn(0).setMinWidth(0);
            tblXoa.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btnbackup.setBackground(new java.awt.Color(25, 29, 74));
        btnbackup.setForeground(new java.awt.Color(25, 29, 74));
        btnbackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/restore1.png"))); // NOI18N
        btnbackup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 29, 74), 50));
        btnbackup.setBorderPainted(false);
        btnbackup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbackupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbackupMouseExited(evt);
            }
        });
        btnbackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(btnbackup, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnbackup, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Đã xóa", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (MessageService.confirm(this, "xoa ko")) {
            this.delete();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tblRomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRomMouseClicked
        this.row = tblRom.getSelectedRow();
        this.edit();
    }//GEN-LAST:event_tblRomMouseClicked

    private void tblXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblXoaMouseClicked
         this.rowRecycle = tblXoa.getSelectedRow();
         this.updateRecycle();
    }//GEN-LAST:event_tblXoaMouseClicked

    private void btnbackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackupActionPerformed
        this.backup();
    }//GEN-LAST:event_btnbackupActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        RomService.fillCombo(QuanLySanPham.romModel, QuanLySanPham.cboRom, QuanLySanPham.listRom);
    }//GEN-LAST:event_formWindowClosed

    private void btnThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseEntered
          changeColor(btnThem, new Color(102, 0, 102));
    }//GEN-LAST:event_btnThemMouseEntered

    private void btnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseExited
      changeColor(btnThem, new Color(25, 29, 74));
    }//GEN-LAST:event_btnThemMouseExited

    private void btnSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseEntered
     changeColor(btnSua, new Color(102, 0, 102));
    }//GEN-LAST:event_btnSuaMouseEntered

    private void btnSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseExited
      changeColor(btnSua, new Color(25, 29, 74));
    }//GEN-LAST:event_btnSuaMouseExited

    private void btnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseEntered
       changeColor(btnXoa, new Color(102, 0, 102));
    }//GEN-LAST:event_btnXoaMouseEntered

    private void btnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseExited
      changeColor(btnXoa, new Color(25, 29, 74));
    }//GEN-LAST:event_btnXoaMouseExited

    private void btnLamMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseEntered
      changeColor(btnLamMoi, new Color(102, 0, 102));
    }//GEN-LAST:event_btnLamMoiMouseEntered

    private void btnLamMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseExited
       changeColor(btnLamMoi, new Color(25, 29, 74));
    }//GEN-LAST:event_btnLamMoiMouseExited

    private void btnbackupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackupMouseEntered
       changeColor(btnbackup, new Color(102, 0, 102));
    }//GEN-LAST:event_btnbackupMouseEntered

    private void btnbackupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackupMouseExited
       changeColor(btnbackup, new Color(25, 29, 74));
    }//GEN-LAST:event_btnbackupMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLRom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLRom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLRom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLRom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLRom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnbackup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblRom;
    private javax.swing.JTable tblXoa;
    private javax.swing.JTextField txtDungLuong;
    private javax.swing.JTextField txtLoaiRam;
    // End of variables declaration//GEN-END:variables

    int row = -1;
    int rowRecycle = -1;
    List<BusRomModel> listRom = new ArrayList<>();
    List<BusRomModel> listRomRecycle = new ArrayList<>();
    DefaultTableModel romModel, romRecycleModel;
    RomService romService = new RomService();

    @Override
    public void init() {
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle("");
        this.fillTable();
        this.fillTableXoa();
    }

    @Override
    public BusRomModel getForm() {
        BusRomModel busRomModel = new BusRomModel();
        busRomModel.setLoaiRon(txtLoaiRam.getText());
        busRomModel.setDungLuongRom(Float.parseFloat(txtDungLuong.getText()));
        return busRomModel;
    }

    @Override
    public void setForm(BusRomModel busRomModel) {
        txtLoaiRam.setText(busRomModel.getLoaiRon());
        txtDungLuong.setText(busRomModel.getDungLuongRom() + "");
    }

    @Override
    public void updateStatus() {
        boolean edit = (this.row >= 0);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
    }

    @Override
    public void insert() {
        BusRomModel busRomModel = this.getForm();
        try {
            romService.insert(busRomModel);
            this.fillTable();
            this.clearForm();
            this.updateStatus();
            MessageService.alert(this, "ok");
        } catch (Exception e) {
            MessageService.alert(this, "err");
        }
    }

    @Override
    public void update() {
        BusRomModel busRomModel = this.getForm();
        int id = (int) tblRom.getValueAt(this.row, 0);
        busRomModel.setMaRom(id);
        try {
            romService.update(busRomModel);
            this.fillTable();
            MessageService.alert(this, "ok");
        } catch (Exception e) {
            MessageService.alert(this, "err");
        }
    }

    @Override
    public void delete() {
        int id = (int) tblRom.getValueAt(this.row, 0);
        try {
            romService.delete(id);
            this.fillTable();
            this.fillTableXoa();
            this.clearForm();
            MessageService.alert(this, "ok");
        } catch (Exception e) {
            MessageService.alert(this, "err");
        }
    }

    @Override
    public void edit() {
        int id = (int) tblRom.getValueAt(this.row, 0);
        BusRomModel busRomModel = this.romService.selectByID(id);
        this.setForm(busRomModel);
        this.updateStatus();
    }

    @Override
    public void clearForm() {
        BusRomModel busRomModel = new BusRomModel();
        this.row = -1;
        this.setForm(busRomModel);
        this.updateStatus();
    }

    @Override
    public void fillTable() {
        this.row = -1;
        this.romModel = (DefaultTableModel) tblRom.getModel();
        this.romModel.setRowCount(0);
        try {
            this.listRom = romService.selectAll();
            this.listRom.forEach((r) -> {
                romModel.addRow(new Object[]{
                    r.getMaRom(),
                    r.getLoaiRon(),
                    r.getDungLuongRom()
                });
            });
            this.updateStatus();
        } catch (Exception e) {
            System.out.println("loi rom");
            e.printStackTrace();
        }
    }
    public void fillTableXoa() {
        this.rowRecycle = -1;
        this.romRecycleModel = (DefaultTableModel) tblXoa.getModel();
        this.romRecycleModel.setRowCount(0);
        try {
            this.listRomRecycle = romService.selectRecycle();
            if(this.listRomRecycle != null) {
                this.listRomRecycle.forEach((r) -> {
                    romRecycleModel.addRow(new Object[]{
                        r.getMaRom(),
                        r.getLoaiRon(),
                        r.getDungLuongRom(),
                    });
                });
            }
            this.updateRecycle();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void backup() {
        int id = (int) tblXoa.getValueAt(this.rowRecycle, 0);
        try {
            romService.backup(id);
            this.fillTable();
            this.fillTableXoa();
            this.updateRecycle();
            MessageService.alert(this, "ok");
        } catch (Exception e) {
            MessageService.alert(this, "err");
        }
    }
    public void updateRecycle() {
        boolean edit = (this.rowRecycle >= 0);
        btnbackup.setEnabled(edit);
    }

    @Override
    public void first() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void last() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void next() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void previous() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean validateForm(boolean isEdit) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
