/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.Models.BusCPUModel;
import BUS.Models.BusCTSanPhamModel;
import BUS.Models.BusCameraModel;
import BUS.Models.BusDongSpModel;
import BUS.Models.BusHangModel;
import BUS.Models.BusHeDieuHanhModel;
import BUS.Models.BusManHinhModel;
import BUS.Models.BusPinModel;
import BUS.Models.BusRamModel;
import BUS.Models.BusRomModel;
import BUS.Models.BusSanPham;
import BUS.Models.BusXuatXuModel;
import BUS.Services.CameraService;
import BUS.Services.CpuService;
import BUS.Services.DongSPService;
import BUS.Services.HangService;
import BUS.Services.HeDieuHanhService;
import BUS.Services.LoaiSPService;
import BUS.Services.ManHinhService;
import BUS.Services.PinService;
import BUS.Services.RamService;
import BUS.Services.RomService;
import BUS.Services.SanPhamService;
import BUS.Services.XuatXuService;
import DAL.Models.DalCTSanPhamModel;
import GUI.Services.IEditService;
import GUI.Services.ImageService;
import GUI.Services.MessageService;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QuanLySanPham extends javax.swing.JInternalFrame implements IEditService<BusCTSanPhamModel> {

    public QuanLySanPham() {
        initComponents();
        this.init();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension d = t.getScreenSize();
        int h = d.height;
        int w = d.width;
        this.setSize(w, h);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel44 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        cboHang = new javax.swing.JComboBox<>();
        btnEditHang3 = new javax.swing.JButton();
        jPanel45 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        cboDongsp = new javax.swing.JComboBox<>();
        btnDong3 = new javax.swing.JButton();
        jPanel46 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        cboCamera = new javax.swing.JComboBox<>();
        btnCamera = new javax.swing.JButton();
        jPanel47 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        cboHeDieuHanh = new javax.swing.JComboBox<>();
        btnHeDieuHanh3 = new javax.swing.JButton();
        jPanel48 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        cboCpu = new javax.swing.JComboBox<>();
        btnCpu3 = new javax.swing.JButton();
        jPanel49 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        cboRom = new javax.swing.JComboBox<>();
        tbnRom3 = new javax.swing.JButton();
        jPanel50 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        cboRam = new javax.swing.JComboBox<>();
        btnRam3 = new javax.swing.JButton();
        jPanel51 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        cboManHinh = new javax.swing.JComboBox<>();
        btnManHinh3 = new javax.swing.JButton();
        txtGiamDan = new javax.swing.JButton();
        btnTangDan = new javax.swing.JButton();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        txtSearchBox = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnLamMoiForm = new javax.swing.JButton();
        jPanel53 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        jPanel54 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        cboXuatXu = new javax.swing.JComboBox<>();
        btnXuatxu = new javax.swing.JButton();
        jPanel55 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        cboPin = new javax.swing.JComboBox<>();
        btnpin = new javax.swing.JButton();
        txtTonKho = new javax.swing.JTextField();
        txtSoluongNhap = new javax.swing.JTextField();
        cboSanPham = new javax.swing.JComboBox<>();
        btnLoaiSanPham = new javax.swing.JButton();

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sp", "Tên sp", "Giá sp", "Ram", "Pin", "CPU", "Rom", "Màn Hình", "Tồn kho"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblSanPham);

        jPanel44.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel61.setText("Hãng SP");
        jPanel44.add(jLabel61);

        cboHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboHangItemStateChanged(evt);
            }
        });
        jPanel44.add(cboHang);

        btnEditHang3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnEditHang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditHang3ActionPerformed(evt);
            }
        });
        jPanel44.add(btnEditHang3);

        jPanel45.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel62.setText("Dòng SP");
        jPanel45.add(jLabel62);

        cboDongsp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDongsp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDongspItemStateChanged(evt);
            }
        });
        jPanel45.add(cboDongsp);

        btnDong3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnDong3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDong3ActionPerformed(evt);
            }
        });
        jPanel45.add(btnDong3);

        jPanel46.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel63.setText("Camera");
        jPanel46.add(jLabel63);

        cboCamera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCamera.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCameraItemStateChanged(evt);
            }
        });
        jPanel46.add(cboCamera);

        btnCamera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCameraActionPerformed(evt);
            }
        });
        jPanel46.add(btnCamera);

        jPanel47.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel64.setText("Hệ điều hành");
        jPanel47.add(jLabel64);

        cboHeDieuHanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboHeDieuHanh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboHeDieuHanhItemStateChanged(evt);
            }
        });
        jPanel47.add(cboHeDieuHanh);

        btnHeDieuHanh3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnHeDieuHanh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeDieuHanh3ActionPerformed(evt);
            }
        });
        jPanel47.add(btnHeDieuHanh3);

        jPanel48.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel65.setText("CPU");
        jPanel48.add(jLabel65);

        cboCpu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCpu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCpuItemStateChanged(evt);
            }
        });
        jPanel48.add(cboCpu);

        btnCpu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnCpu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCpu3ActionPerformed(evt);
            }
        });
        jPanel48.add(btnCpu3);

        jPanel49.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel66.setText("Bộ nhớ trong");
        jPanel49.add(jLabel66);

        cboRom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboRom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboRomItemStateChanged(evt);
            }
        });
        jPanel49.add(cboRom);

        tbnRom3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        tbnRom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnRom3ActionPerformed(evt);
            }
        });
        jPanel49.add(tbnRom3);

        jPanel50.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel67.setText("Dung lượng RAM");
        jPanel50.add(jLabel67);

        cboRam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboRam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboRamItemStateChanged(evt);
            }
        });
        jPanel50.add(cboRam);

        btnRam3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnRam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRam3ActionPerformed(evt);
            }
        });
        jPanel50.add(btnRam3);

        jPanel51.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel68.setText("Màn hình");
        jPanel51.add(jLabel68);

        cboManHinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboManHinh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboManHinhItemStateChanged(evt);
            }
        });
        jPanel51.add(cboManHinh);

        btnManHinh3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnManHinh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManHinh3ActionPerformed(evt);
            }
        });
        jPanel51.add(btnManHinh3);

        txtGiamDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sort.png"))); // NOI18N
        txtGiamDan.setText("Giá cao");
        txtGiamDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamDanActionPerformed(evt);
            }
        });

        btnTangDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tang.png"))); // NOI18N
        btnTangDan.setText("Giá thấp");
        btnTangDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangDanbtnTangDanActionPerformed(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel69.setText("Sắp xếp theo");

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel70.setText("Tìm kiếm");

        txtSearchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchBoxsearch(evt);
            }
        });

        lblImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });

        jPanel52.setLayout(new java.awt.GridLayout(1, 0, 3, 0));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel52.add(btnXoa);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel52.add(btnSua);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel52.add(btnThem);

        btnLamMoiForm.setText("Làm mới");
        btnLamMoiForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiFormActionPerformed(evt);
            }
        });
        jPanel52.add(btnLamMoiForm);

        jPanel53.setLayout(new java.awt.GridLayout(1, 0, 3, 0));

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel53.add(btnFirst);

        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel53.add(btnBack);

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel53.add(btnNext);

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        jPanel53.add(btnLast);

        jLabel71.setText("Tên sản phẩm");

        txtMota.setColumns(20);
        txtMota.setRows(5);
        jScrollPane8.setViewportView(txtMota);

        jLabel72.setText("Mô tả");

        jLabel73.setText("Giá nhập");

        jLabel74.setText("Giá bán");

        jLabel75.setText("Tồn kho");

        jLabel76.setText("Số lượng nhập");

        jLabel77.setText("VNĐ");

        jLabel78.setText("VNĐ");

        txtGiaNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtGiaNhap.setForeground(new java.awt.Color(255, 0, 51));

        txtGiaBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtGiaBan.setForeground(new java.awt.Color(255, 0, 51));

        jPanel54.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel79.setText("Xuất xứ");
        jPanel54.add(jLabel79);

        cboXuatXu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboXuatXu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboXuatXuItemStateChanged(evt);
            }
        });
        jPanel54.add(cboXuatXu);

        btnXuatxu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnXuatxu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatxuActionPerformed(evt);
            }
        });
        jPanel54.add(btnXuatxu);

        jPanel55.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel80.setText("Pin");
        jPanel55.add(jLabel80);

        cboPin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPinItemStateChanged(evt);
            }
        });
        jPanel55.add(cboPin);

        btnpin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpinActionPerformed(evt);
            }
        });
        jPanel55.add(btnpin);

        txtTonKho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTonKho.setForeground(new java.awt.Color(255, 0, 51));

        txtSoluongNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSoluongNhap.setForeground(new java.awt.Color(255, 0, 51));

        cboSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnLoaiSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel49, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(383, 383, 383))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jPanel48, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel69)
                                    .addGap(389, 389, 389)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnTangDan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGiamDan)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel71)
                            .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel78))
                            .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel77))
                                .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSoluongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel52, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboSanPham, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel69)
                            .addComponent(jLabel70, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnTangDan)
                                .addComponent(txtGiamDan))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel71)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel74)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel78))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel75)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel72)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel73)
                            .addComponent(jLabel76))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel77)
                            .addComponent(txtSoluongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboSanPham, txtGiaBan, txtTonKho});

        jTabbedPane4.addTab("Sản phẩm", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTangDanbtnTangDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangDanbtnTangDanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTangDanbtnTangDanActionPerformed

    private void txtSearchBoxsearch(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBoxsearch
        this.fillTable();
    }//GEN-LAST:event_txtSearchBoxsearch

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        this.selectImage();
    }//GEN-LAST:event_lblImageMouseClicked

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        this.row = tblSanPham.getSelectedRow();
        this.edit();
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void cboRomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboRomItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {

        }
    }//GEN-LAST:event_cboRomItemStateChanged

    private void cboRamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboRamItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {

        }
    }//GEN-LAST:event_cboRamItemStateChanged

    private void cboManHinhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboManHinhItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboManHinhItemStateChanged

    private void cboHeDieuHanhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboHeDieuHanhItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboHeDieuHanhItemStateChanged

    private void cboHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboHangItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
//            this.fillDongCombo();
        }
    }//GEN-LAST:event_cboHangItemStateChanged

    private void cboCpuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCpuItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCpuItemStateChanged

    private void cboDongspItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDongspItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDongspItemStateChanged

    private void cboXuatXuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboXuatXuItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboXuatXuItemStateChanged

    private void cboCameraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCameraItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCameraItemStateChanged

    private void cboPinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPinItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPinItemStateChanged

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiFormActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnLamMoiFormActionPerformed

    private void tbnRom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnRom3ActionPerformed
        new QLRom().setVisible(true);
    }//GEN-LAST:event_tbnRom3ActionPerformed

    private void btnManHinh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManHinh3ActionPerformed
        new QLManHinh().setVisible(true);
    }//GEN-LAST:event_btnManHinh3ActionPerformed

    private void btnEditHang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditHang3ActionPerformed
        new QLHangsp().setVisible(true);
    }//GEN-LAST:event_btnEditHang3ActionPerformed

    private void btnDong3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDong3ActionPerformed
        new QLDongSP().setVisible(true);
    }//GEN-LAST:event_btnDong3ActionPerformed

    private void btnCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCameraActionPerformed
        new QLCameraSp().setVisible(true);
    }//GEN-LAST:event_btnCameraActionPerformed

    private void btnCpu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCpu3ActionPerformed
        new QLCPU().setVisible(true);
    }//GEN-LAST:event_btnCpu3ActionPerformed

    private void btnXuatxuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatxuActionPerformed
        new QLXuatXu().setVisible(true);
    }//GEN-LAST:event_btnXuatxuActionPerformed

    private void btnpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpinActionPerformed
        new QLPin().setVisible(true);
    }//GEN-LAST:event_btnpinActionPerformed

    private void btnHeDieuHanh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeDieuHanh3ActionPerformed
        new QLHeDieuHanh().setVisible(true);
    }//GEN-LAST:event_btnHeDieuHanh3ActionPerformed

    private void btnRam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRam3ActionPerformed
        new QLRam().setVisible(true);
    }//GEN-LAST:event_btnRam3ActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        this.first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.previous();    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        this.next();    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        this.last();    }//GEN-LAST:event_btnLastActionPerformed

    private void txtGiamDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamDanActionPerformed
        this.sortDesc();
    }//GEN-LAST:event_txtGiamDanActionPerformed

    private void btnTangDanbtnTangDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangDanbtnTangDanActionPerformed
       this.sortAsend();
    }//GEN-LAST:event_btnTangDanbtnTangDanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCamera;
    private javax.swing.JButton btnCpu3;
    private javax.swing.JButton btnDong3;
    private javax.swing.JButton btnEditHang3;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnHeDieuHanh3;
    private javax.swing.JButton btnLamMoiForm;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLoaiSanPham;
    private javax.swing.JButton btnManHinh3;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnRam3;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTangDan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatxu;
    private javax.swing.JButton btnpin;
    private javax.swing.JComboBox<String> cboCamera;
    private javax.swing.JComboBox<String> cboCpu;
    private javax.swing.JComboBox<String> cboDongsp;
    private javax.swing.JComboBox<String> cboHang;
    private javax.swing.JComboBox<String> cboHeDieuHanh;
    private javax.swing.JComboBox<String> cboManHinh;
    private javax.swing.JComboBox<String> cboPin;
    private javax.swing.JComboBox<String> cboRam;
    private javax.swing.JComboBox<String> cboRom;
    private javax.swing.JComboBox<String> cboSanPham;
    private javax.swing.JComboBox<String> cboXuatXu;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JButton tbnRom3;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JButton txtGiamDan;
    private javax.swing.JTextArea txtMota;
    private javax.swing.JTextField txtSearchBox;
    private javax.swing.JTextField txtSoluongNhap;
    private javax.swing.JTextField txtTonKho;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel modelSp;
    DefaultComboBoxModel<BusCameraModel> cameraModel;
    DefaultComboBoxModel<BusCPUModel> cpuModel;
    DefaultComboBoxModel<BusDongSpModel> dongspModel;
    DefaultComboBoxModel<BusHangModel> hangspModel;
    DefaultComboBoxModel<BusHeDieuHanhModel> heDieuHanhModel;
    DefaultComboBoxModel<BusManHinhModel> manHinhModel;
    DefaultComboBoxModel<BusPinModel> pinModel;
    DefaultComboBoxModel<BusRamModel> ramModel;
    DefaultComboBoxModel<BusRomModel> romModel;
    DefaultComboBoxModel<BusXuatXuModel> xuatXuModel;
    DefaultComboBoxModel<BusSanPham> sanPhamModel;

    SanPhamService sanPhamService = new SanPhamService();
    LoaiSPService loaiSPService = new LoaiSPService();
    CameraService cameraService = new CameraService();
    CpuService cpuService = new CpuService();
    DongSPService dongSPService = new DongSPService();
    HangService hangService = new HangService();
    HeDieuHanhService heDieuHanhService = new HeDieuHanhService();
    ManHinhService manHinhService = new ManHinhService();
    PinService pinService = new PinService();
    RamService ramService = new RamService();
    RomService romService = new RomService();
    XuatXuService xuatXuService = new XuatXuService();
    int row = -1;

    List<BusCTSanPhamModel> listSp = new ArrayList<>();
    List<BusCameraModel> listCamera = new ArrayList<>();
    List<BusCPUModel> listCpu = new ArrayList<>();
    List<BusDongSpModel> listDong = new ArrayList<>();
    List<BusHangModel> listHang = new ArrayList<>();
    List<BusHeDieuHanhModel> listHeDieuHanh = new ArrayList<>();
    List<BusManHinhModel> listManHinh = new ArrayList<>();
    List<BusPinModel> listPin = new ArrayList<>();
    List<BusRamModel> listRam = new ArrayList<>();
    List<BusRomModel> listRom = new ArrayList<>();
    List<BusXuatXuModel> listXuatXu = new ArrayList<>();
    List<BusSanPham> listLoaisp = new ArrayList<>();

    @Override
    public void init() {
        this.setTitle("Quan ly sp");
        this.updateStatus();
        this.fillTable();
        this.fillRomCombo();
        this.fillCameraCombo();
        this.fillCPUCombo();
        this.fillHangCombo();
        this.fillHeDieuHanhCombo();
        this.fillManHinhCombo();
        this.fillPinCombo();
        this.fillRamCombo();
        this.fillXuatXuCombo();
        this.fillTenSanPhamCombo();

    }

    @Override
    public void setForm(BusCTSanPhamModel sp) {
        if (sp.getHinh() != null) {
            lblImage.setToolTipText(sp.getHinh());
            lblImage.setIcon(ImageService.readImage(sp.getHinh(), lblImage));
        } else {
            lblImage.setToolTipText(null);
            lblImage.setIcon(null);
        }
        txtTonKho.setText(sp.getTonKho() + "");
        txtGiaBan.setText(sp.getGiaBan() + "");
        txtGiaNhap.setText(sp.getGiaNhap() + "");
        txtSoluongNhap.setText(sp.getSoLuongNhap() + "");
        txtMota.setText(sp.getMota());
//        txtTenSp.setText(sp.getSanPhamModel() != null ? sp.getSanPhamModel().getTensp() : "");

    }

    @Override
    public void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblSanPham.getRowCount() - 1);

        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);

        btnFirst.setEnabled(edit && !first);
        btnLast.setEnabled(edit && !last);
        btnNext.setEnabled(edit && !last);
        btnBack.setEnabled(edit && !first);
    }

    public DalCTSanPhamModel getInfoForm() {
        DalCTSanPhamModel sp = new DalCTSanPhamModel();
        sp.setGiaBan(Float.parseFloat(txtGiaBan.getText()));
        sp.setGiaNhap(Float.parseFloat(txtGiaNhap.getText()));
        sp.setSoLuongNhap(Integer.parseInt(txtSoluongNhap.getText()));
        sp.setNgayNhap(new Date());
        sp.setTonKho(Integer.parseInt(txtTonKho.getText()));
        sp.setHinh(lblImage.getToolTipText());
        sp.setMota(txtMota.getText());
        
//        BusCameraModel busCameraModel = (BusCameraModel) cboCamera.getSelectedItem();
//        sp.setMaCamera(busCameraModel.getMaCamera());
        sp.setMaCamera(3);
        BusCPUModel busCPUModel = (BusCPUModel) cboCpu.getSelectedItem();
        sp.setMaSp(busCPUModel.getMaCPU());
        sp.setMaCpu(2);
        
        BusSanPham busSanPham = (BusSanPham) cboSanPham.getSelectedItem();
        sp.setMaSp(busSanPham.getMasp());
        
        BusHeDieuHanhModel busHeDieuHanhModel = (BusHeDieuHanhModel) cboHeDieuHanh.getSelectedItem();
        sp.setMaHeDieuHanh(Integer.parseInt(busHeDieuHanhModel.getMaHeDieuHanh()));
        
        BusManHinhModel busManHinhModel = (BusManHinhModel) cboManHinh.getSelectedItem();
        sp.setMaManHinh(Integer.parseInt(busManHinhModel.getMaManHinh()));
        
        BusRamModel busRamModel = (BusRamModel) cboRam.getSelectedItem();
        sp.setMaRam(busRamModel.getMaRam());
        
        BusPinModel busPinModel = (BusPinModel) cboPin.getSelectedItem();
        sp.setMaLoaiPin(Integer.parseInt(busPinModel.getMaLoaiPin()));
        
        
        BusRomModel busRomModel = (BusRomModel) cboRom.getSelectedItem();
        sp.setMaRom(busRomModel.getMaRom());
        
        BusXuatXuModel busXuatXuModel = (BusXuatXuModel) cboXuatXu.getSelectedItem();
        sp.setMaXuatXu(busXuatXuModel.getMaXuatXu());
        
        return sp;
    }

    @Override
    public void insert() {
        DalCTSanPhamModel sp = this.getInfoForm();
        try {
            sanPhamService.insert(sp);
            this.clearForm();
            this.fillTable();
            MessageService.alert(this, "yeahhhh");
        } catch (Exception e) {
            MessageService.alert(this, "error");
        }
    }

    @Override
    public void update() {
        DalCTSanPhamModel sp = this.getInfoForm();
        try {
            sanPhamService.insert(sp);
            this.fillTable();
            MessageService.alert(this, "yeahhhh");
        } catch (Exception e) {
            MessageService.alert(this, "error");
        }
    }

    @Override
    public void delete() {
        int id = (int) tblSanPham.getValueAt(row, 0);
        try {
            sanPhamService.delete(id);
            this.clearForm();
            this.fillTable();
            MessageService.alert(this, "yeahhhh");
        } catch (Exception e) {
            MessageService.alert(this, "error");
        }
    }

    @Override
    public void edit() {
        int id = (int) tblSanPham.getValueAt(row, 0);
        BusCTSanPhamModel sp = new BusCTSanPhamModel();
        try {
            sp = sanPhamService.selectID(id);
            this.setForm(sp);
            this.updateStatus();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void clearForm() {
        this.row = -1;
        BusCTSanPhamModel sp = new BusCTSanPhamModel();
        this.setForm(sp);
        this.updateStatus();
    }

    @Override
    public void fillTable() {
        this.modelSp = (DefaultTableModel) tblSanPham.getModel();
        modelSp.setRowCount(0);
        String keyWord = txtSearchBox.getText();
        try {
            this.listSp = sanPhamService.selectBySearch(keyWord);
            System.out.println("ko phai csdl");
            this.listSp.forEach(sp -> {
                this.modelSp.addRow(new Object[]{
                    sp.getMaCTSP(),
                    sp.getSanPhamModel().getTensp(),
                    sp.getGiaBan() + " VNĐ",
                    sp.getRamModel().getDungLuongRam() + " gb",
                    sp.getPinModel().getDungLuongPin() + " mnAh",
                    sp.getcPUModel().getTenCPU(),
                    sp.getRomModel().getDungLuongRom() + " gb",
                    sp.getManHinhModel().getKichThuoc() + " inch",
                    sp.getTonKho()
                });
            });
        } catch (Exception e) {
            MessageService.alert(this, "loi");
        }
    }

    void selectImage() {
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            ImageService.save(file);
            ImageIcon icon = ImageService.readImage(file.getName(), lblImage);
            lblImage.setIcon(icon);
            lblImage.setToolTipText(file.getName());
        }

    }

    void fillCameraCombo() {
        this.cameraModel = (DefaultComboBoxModel) cboCamera.getModel();
        this.cameraModel.removeAllElements();
        try {
            this.listCamera = cameraService.selectAll();
            if (this.listCamera != null) {
                for (BusCameraModel cam : this.listCamera) {
                    this.cameraModel.addElement(cam);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillCPUCombo() {
        this.cpuModel = (DefaultComboBoxModel) cboCpu.getModel();
        this.cpuModel.removeAllElements();
        try {
            this.listCpu = cpuService.selectAll();
            if (this.listCpu != null) {
                for (BusCPUModel cpu : this.listCpu) {
                    this.cpuModel.addElement(cpu);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillDongCombo() {
        this.dongspModel = (DefaultComboBoxModel) cboDongsp.getModel();
        this.dongspModel.removeAllElements();
        try {
            this.listDong = dongSPService.selectAll();
            if (this.listDong != null) {
                for (BusDongSpModel dong : this.listDong) {
                    this.dongspModel.addElement(dong);
                }
            }
            this.fillTenSanPhamCombo();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    void fillTenSanPhamCombo() {
        this.sanPhamModel = (DefaultComboBoxModel) cboSanPham.getModel();
        this.sanPhamModel.removeAllElements();
        try {
            this.listLoaisp = loaiSPService.selectBySearch("");
            if (this.listLoaisp != null) {
                for (BusSanPham sp : this.listLoaisp) {
                    this.sanPhamModel.addElement(sp);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillHangCombo() {
        this.hangspModel = (DefaultComboBoxModel) cboHang.getModel();
        this.hangspModel.removeAllElements();
        try {
            this.listHang = hangService.selectAll();
            if (this.listHang != null) {
                for (BusHangModel hang : this.listHang) {
                    this.hangspModel.addElement(hang);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillHeDieuHanhCombo() {
        this.heDieuHanhModel = (DefaultComboBoxModel) cboHeDieuHanh.getModel();
        this.heDieuHanhModel.removeAllElements();
        try {
            this.listHeDieuHanh = heDieuHanhService.selectAll();
            if (this.listHeDieuHanh != null) {
                for (BusHeDieuHanhModel he : this.listHeDieuHanh) {
                    this.heDieuHanhModel.addElement(he);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillManHinhCombo() {
        this.manHinhModel = (DefaultComboBoxModel) cboManHinh.getModel();
        this.manHinhModel.removeAllElements();
        try {
            this.listManHinh = manHinhService.selectAll();
            if (this.listManHinh != null) {
                for (BusManHinhModel screen : this.listManHinh) {
                    this.manHinhModel.addElement(screen);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        fillDongCombo();
    }

    void fillPinCombo() {
        this.pinModel = (DefaultComboBoxModel) cboPin.getModel();
        this.pinModel.removeAllElements();
        try {
            this.listPin = pinService.selectAll();
            if (this.listPin != null) {
                for (BusPinModel pin : this.listPin) {
                    this.pinModel.addElement(pin);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillRamCombo() {
        this.ramModel = (DefaultComboBoxModel) cboRam.getModel();
        this.ramModel.removeAllElements();
        try {
            this.listRam = ramService.selectAll();
            if (this.listRam != null) {
                for (BusRamModel ram : this.listRam) {
                    this.ramModel.addElement(ram);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillRomCombo() {
        this.romModel = (DefaultComboBoxModel) cboRom.getModel();
        this.romModel.removeAllElements();
        try {
            this.listRom = romService.selectAll();
            if (this.listRom != null) {
                for (BusRomModel rom : this.listRom) {
                    this.romModel.addElement(rom);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void fillXuatXuCombo() {
        this.xuatXuModel = (DefaultComboBoxModel) cboXuatXu.getModel();
        this.xuatXuModel.removeAllElements();
        try {
            this.listXuatXu = xuatXuService.selectAll();
            if (this.listXuatXu != null) {
                for (BusXuatXuModel xuatXu : this.listXuatXu) {
                    this.xuatXuModel.addElement(xuatXu);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    Comparator<BusCTSanPhamModel> comparator = Comparator.comparing(BusCTSanPhamModel::getGiaBan);
    void sortDesc() {
        System.out.println("bat dau sort");
        Collections.sort(listSp, comparator);
        System.out.println("sort ok");
        this.listSp.forEach(sp -> {
                System.out.println(sp.getGiaBan() + "");
            });
        this.fill();
    }

    void fill() {
        modelSp = (DefaultTableModel) tblSanPham.getModel();
        modelSp.setRowCount(0);
        this.clearForm();
        if (this.listSp.size() > 0) {
            this.listSp.forEach(sp -> {
                this.modelSp.addRow(new Object[]{
                    sp.getMaCTSP(),
                    sp.getSanPhamModel().getTensp(),
                    sp.getGiaBan() + " VNĐ",
                    sp.getRamModel().getDungLuongRam() + " gb",
                    sp.getPinModel().getDungLuongPin() + " mnAh",
                    sp.getcPUModel().getTenCPU(),
                    sp.getRomModel().getDungLuongRom() + " gb",
                    sp.getManHinhModel().getKichThuoc() + " inch",
                    sp.getTonKho()
                });
            });
        }
    }

    void sortAsend() {
        Collections.sort(listSp, comparator);
        Collections.reverse(listSp);
        this.fill();
    }
    @Override
    public void first() {
        this.row = 0;
        this.edit();
    }

    @Override
    public void last() {
        this.row = tblSanPham.getRowCount() - 1;
        this.edit();
    }

    @Override
    public void next() {
        if (this.row < tblSanPham.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    @Override
    public void previous() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }
    void sortDesc() {
        Comparator<BusCTSanPhamModel> comparator = new Comparator<BusCTSanPhamModel>() {
            @Override
            public int compare(BusCTSanPhamModel o1, BusCTSanPhamModel o2) {
                return Float.compare(o1.getGiaBan(), o2.getGiaBan());
            }
        };
        
    }
    void sortAsend() {
        
    }
    @Override
    public boolean validateForm(boolean isEdit) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public BusCTSanPhamModel getForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
