/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.Models.BusPinModel;
import BUS.Models.KhachHangModel;
import BUS.Services.KhachHangService;
import DAL.Models.NhanVienModel;
import GUI.Services.ButtonColumn;
import GUI.Services.DateService;
import GUI.Services.IEditService;
import GUI.Services.MessageService;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DUCNAM
 */
public class QuanLyKhachHang extends javax.swing.JInternalFrame implements IEditService<KhachHangModel> {

    DefaultTableModel modelkh = new DefaultTableModel();
    Icon icon = new ImageIcon(getClass().getResource("/icon/curve-arrow.png"));
    KhachHangService khser = new KhachHangService();
    int row = -1;

    /**
     * Creates new form QuanLyKhachHang
     */
    public QuanLyKhachHang() {
        initComponents();
        init();

    }
//    public void showPopUp(MouseEvent e) {
//        PopMenu.show(this, e.getX(), e.getY());
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrpGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tkTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tkcboTuoi = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tk2cboTuoi = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        chktimkiem = new javax.swing.JCheckBox();
        tabs = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtHoTenKH2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        rdoNam2 = new javax.swing.JRadioButton();
        rdoNu2 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        txtSDT2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtDiaCHi2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btnThem2 = new javax.swing.JButton();
        btnSua2 = new javax.swing.JButton();
        btnXoa2 = new javax.swing.JButton();
        btnMoi2 = new javax.swing.JButton();
        txtNgayTao2 = new com.toedter.calendar.JDateChooser();
        txtNgaySinh2 = new com.toedter.calendar.JDateChooser();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtGhiChu2 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang2 = new javax.swing.JTable();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Tên");

        tkTen.setEditable(false);
        tkTen.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tkTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tkTenKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Khoảng tuổi");

        tkcboTuoi.setEnabled(false);
        tkcboTuoi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tkcboTuoiItemStateChanged(evt);
            }
        });
        tkcboTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkcboTuoiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("-");

        tk2cboTuoi.setEnabled(false);
        tk2cboTuoi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tk2cboTuoiItemStateChanged(evt);
            }
        });
        tk2cboTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk2cboTuoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tkcboTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)
                                .addComponent(tk2cboTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tkTen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tk2cboTuoi, tkcboTuoi});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tkTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tkcboTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addComponent(tk2cboTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Khách hàng");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, -1, -1));

        chktimkiem.setText("Tick");
        chktimkiem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chktimkiemItemStateChanged(evt);
            }
        });
        jPanel1.add(chktimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 256, -1, -1));

        tabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabsMouseClicked(evt);
            }
        });

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Tên KH", "SDT", "Địa chỉ", "Giới tính", "Ngày sinh", "Ngày tạo", "Ghi chú", "Số lần mua"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang.setRowHeight(25);
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblKhachHang);
        if (tblKhachHang.getColumnModel().getColumnCount() > 0) {
            tblKhachHang.getColumnModel().getColumn(0).setMinWidth(50);
            tblKhachHang.getColumnModel().getColumn(0).setMaxWidth(50);
            tblKhachHang.getColumnModel().getColumn(4).setMinWidth(70);
            tblKhachHang.getColumnModel().getColumn(4).setMaxWidth(70);
            tblKhachHang.getColumnModel().getColumn(8).setMinWidth(70);
            tblKhachHang.getColumnModel().getColumn(8).setMaxWidth(70);
        }

        jPanel9.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1355, 567));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Điều hướng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N

        btnFirst.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(btnFirst)
                .addGap(10, 10, 10)
                .addComponent(btnPrev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLast)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFirst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 852, -1, -1));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm,sửa xóa khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 15))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel20.setText("Họ và tên");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 32, -1, -1));

        txtHoTenKH2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jPanel10.add(txtHoTenKH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 59, 198, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel21.setText("Giới tính");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 103, -1, -1));

        bgrpGender.add(rdoNam2);
        rdoNam2.setSelected(true);
        rdoNam2.setText("Nam");
        jPanel10.add(rdoNam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 126, -1, -1));

        bgrpGender.add(rdoNu2);
        rdoNu2.setText("Nữ");
        jPanel10.add(rdoNu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 126, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel22.setText("Số điện thoại");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 161, -1, -1));

        txtSDT2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jPanel10.add(txtSDT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 188, 198, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel23.setText("Địa chỉ");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 32, -1, -1));

        txtDiaCHi2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jPanel10.add(txtDiaCHi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 59, 268, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel24.setText("Ngày sinh");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 100, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel25.setText("Ngày tạo");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 158, -1, -1));

        jPanel11.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        btnThem2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnThem2.setText("Thêm");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });
        jPanel11.add(btnThem2);

        btnSua2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnSua2.setText("Sửa");
        btnSua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua2ActionPerformed(evt);
            }
        });
        jPanel11.add(btnSua2);

        btnXoa2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnXoa2.setText("Xóa");
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2ActionPerformed(evt);
            }
        });
        jPanel11.add(btnXoa2);

        btnMoi2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnMoi2.setText("Mới");
        btnMoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoi2ActionPerformed(evt);
            }
        });
        jPanel11.add(btnMoi2);

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 21, 134, 211));
        jPanel10.add(txtNgayTao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 190, 268, -1));
        jPanel10.add(txtNgaySinh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 127, 268, -1));

        txtGhiChu2.setColumns(20);
        txtGhiChu2.setRows(5);
        jScrollPane5.setViewportView(txtGhiChu2);

        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 54, 258, 156));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel26.setText("Ghi chú");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 32, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 596, 1355, -1));

        tabs.addTab("Khách hàng", jPanel9);

        tblKhachHang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "SDT", "Địa chỉ", "Giới tính", "Ngày sình", "Ngày tạo", "Ghi chú", "Số lần mua", "Khôi phục"
            }
        ));
        tblKhachHang2.setRowHeight(25);
        jScrollPane1.setViewportView(tblKhachHang2);
        if (tblKhachHang2.getColumnModel().getColumnCount() > 0) {
            tblKhachHang2.getColumnModel().getColumn(9).setMinWidth(70);
            tblKhachHang2.getColumnModel().getColumn(9).setMaxWidth(70);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1375, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
        );

        tabs.addTab("Đã xóa", jPanel6);

        jPanel1.add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 979));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        for (int i = 1; i < 71; i++) {
            tkcboTuoi.addItem(String.valueOf(i));
        }
        for (int i = 1; i < 71; i++) {
            tk2cboTuoi.addItem(String.valueOf(i));
        }
    }//GEN-LAST:event_formComponentShown

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        //       if (evt.isPopupTrigger()) {
        //            showPopUp(evt);
        //        }
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        //       if (evt.isPopupTrigger()) {
        //            showPopUp(evt);
        //        }
    }//GEN-LAST:event_jPanel1MousePressed

    private void chktimkiemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chktimkiemItemStateChanged
        if (chktimkiem.isSelected() == false) {
            tkTen.setEditable(false);
            tkcboTuoi.setEnabled(false);
            tk2cboTuoi.setEnabled(false);
            tkTen.setText("");
            tkcboTuoi.setSelectedIndex(0);
            tk2cboTuoi.setSelectedIndex(0);
            fillTable();
            fillTable2();
        } else {
            tkTen.setEditable(true);
            tkcboTuoi.setEnabled(true);
            tk2cboTuoi.setEnabled(true);
        }

    }//GEN-LAST:event_chktimkiemItemStateChanged

    private void tk2cboTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk2cboTuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk2cboTuoiActionPerformed

    private void tk2cboTuoiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tk2cboTuoiItemStateChanged
        if (chktimkiem.isSelected()) {
            if (tabs.getSelectedIndex() == 0) {
                timkiemTuoi();
                clearForm();
                row = -1;
                updateStatus();
            }
            if (tabs.getSelectedIndex() == 1) {
                timkiemTuoi2();
                row = -1;
            }

        }

    }//GEN-LAST:event_tk2cboTuoiItemStateChanged

    private void tkcboTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkcboTuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkcboTuoiActionPerformed

    private void tkcboTuoiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tkcboTuoiItemStateChanged

        DefaultComboBoxModel tuoimodel = new DefaultComboBoxModel();
        tk2cboTuoi.setModel(tuoimodel);
        for (int i = tkcboTuoi.getSelectedIndex() + 1; i < 70; i++) {
            tk2cboTuoi.addItem(String.valueOf(i));
        }

    }//GEN-LAST:event_tkcboTuoiItemStateChanged

    private void tkTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tkTenKeyReleased
        if (chktimkiem.isSelected()) {
            if (tabs.getSelectedIndex() == 0) {
                timkiemTen();
                clearForm();
                row = -1;
                updateStatus();
            }
            if (tabs.getSelectedIndex() == 1) {
                timkiemTen2();
                row = -1;
            }
        }

    }//GEN-LAST:event_tkTenKeyReleased

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        previous();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here: this.index = 0;
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        if (evt.getClickCount() == 1) {
            this.row = tblKhachHang.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void tabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabsMouseClicked
        // TODO add your handling code here:
        if (tabs.getSelectedIndex() == 0) {
//            clearForm();
            updateStatus();

        } else {
//            clearForm();
            chktimkiem.setSelected(false);

        }
    }//GEN-LAST:event_tabsMouseClicked

    private void btnSua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua2ActionPerformed
        if(chekrong()==true){
            if(checkvai()==true){
                update();
            }
        }
    }//GEN-LAST:event_btnSua2ActionPerformed

    private void btnXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2ActionPerformed
       delete();
    }//GEN-LAST:event_btnXoa2ActionPerformed

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
         if(chekrong()==true){
            if(checkvai()==true){
                insert();
            }
        }
    }//GEN-LAST:event_btnThem2ActionPerformed

    private void btnMoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoi2ActionPerformed
        clearForm();
    }//GEN-LAST:event_btnMoi2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrpGender;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi2;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua2;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JCheckBox chktimkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton rdoNam2;
    private javax.swing.JRadioButton rdoNu2;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTable tblKhachHang2;
    public static javax.swing.JComboBox<String> tk2cboTuoi;
    private javax.swing.JTextField tkTen;
    public static javax.swing.JComboBox<String> tkcboTuoi;
    private javax.swing.JTextField txtDiaCHi2;
    private javax.swing.JTextArea txtGhiChu2;
    private javax.swing.JTextField txtHoTenKH2;
    private com.toedter.calendar.JDateChooser txtNgaySinh2;
    private com.toedter.calendar.JDateChooser txtNgayTao2;
    private javax.swing.JTextField txtSDT2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init() {
        this.setSize();
        fillTable();
        fillTable2();
        updateStatus();
        this.row = -1;
        buttonintable();
        
        
        txtNgayTao2.setDate(DateService.now());

    }

    @Override
    public KhachHangModel getForm() {

        KhachHangModel kh = new KhachHangModel();
        kh.setTenKH(txtHoTenKH2.getText());
        kh.setGioiTinh(rdoNam2.isSelected());
        kh.setSDT(txtSDT2.getText());
        kh.setDiaChi(txtDiaCHi2.getText());
        kh.setNgaySinh(txtNgaySinh2.getDate());
        kh.setNgayTao(txtNgayTao2.getDate());
        kh.setGhiChu(txtGhiChu2.getText());

        return kh;

    }

    @Override
    public void setForm(KhachHangModel entity) {
        txtHoTenKH2.setText(entity.getTenKH());
        rdoNam2.setSelected(entity.isGioiTinh());
        rdoNu2.setSelected(!entity.isGioiTinh());
        txtSDT2.setText(entity.getSDT());
        txtDiaCHi2.setText(entity.getDiaChi());
        txtNgaySinh2.setDate(entity.getNgaySinh());
        txtNgayTao2.setDate(entity.getNgayTao());
        txtGhiChu2.setText(entity.getGhiChu());
    }

    @Override
    public void updateStatus() {
        boolean edit = (row >= 0);
        boolean first = (row == 0);
        boolean last = (row == tblKhachHang.getRowCount() - 1);

        btnThem2.setEnabled(!edit);
        btnSua2.setEnabled(edit);
        btnXoa2.setEnabled(edit);
        btnMoi2.setEnabled(edit);

        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
    }

    @Override
    public void insert() {
        KhachHangModel kh = getForm();
        try {
            khser.insert(kh);
            this.fillTable();

            MessageService.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            MessageService.alert(this, "Thêm mới thất bại!");
            e.printStackTrace();
        }

    }

    @Override
    public void update() {
        KhachHangModel khModel = this.getForm();
        int id = (int) tblKhachHang.getValueAt(this.row, 0);
        khModel.setMaKH(id);
        try {
            khser.update(khModel);

            this.fillTable();
            this.fillTable2();
            MessageService.alert(this, "Update thành công");
        } catch (Exception e) {
            MessageService.alert(this, "Update thất bại");

        }
    }

    @Override
    public void delete() {
        try {
            if (MessageService.confirm(this, "Bạn có muốn xóa khách hàng này không?")) {
                for (int row : tblKhachHang.getSelectedRows()) {
                    int makh = (Integer) tblKhachHang.getValueAt(row, 0);
                    khser.delete(makh);
                }
                MessageService.alert(this, "xóa thành công");
                fillTable();
                fillTable2();
            }
        } catch (Exception e) {
            MessageService.alert(this, "Xóa thất bại");

        }

    }

    @Override
    public void edit() {

        int idkh = (Integer) tblKhachHang.getValueAt(this.row, 0);
        KhachHangModel khmodel = this.khser.selectByID(idkh);
        setForm(khmodel);
        updateStatus();

    }

    @Override
    public void clearForm() {
        KhachHangModel khmodel = new KhachHangModel();
        this.row = -1;
        this.setForm(khmodel);
        this.updateStatus();
    }

    @Override
    public void fillTable() {

        DefaultTableModel modelkh = (DefaultTableModel) tblKhachHang.getModel();
        modelkh.setRowCount(0);
        try {
            List<KhachHangModel> list = khser.selectAll1();

            for (KhachHangModel kh : list) {
                Object[] row = {
                    kh.getMaKH(),
                    kh.getTenKH(),
                    kh.getSDT(),
                    kh.getDiaChi(),
                    kh.isGioiTinh() ? "Nam" : "Nữ",
                    kh.getNgaySinh(),
                    kh.getNgayTao(),
                    kh.getGhiChu(),
                    kh.getSoLanMua()};
                modelkh.addRow(row);
            }

        } catch (Exception e) {
            MessageService.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();

        }
    }

    public void fillTable2() {

        DefaultTableModel modelkh = (DefaultTableModel) tblKhachHang2.getModel();
        modelkh.setRowCount(0);
        try {
            List<KhachHangModel> list = khser.selectAll2();

            for (KhachHangModel kh : list) {
                Object[] row = {
                    kh.getMaKH(),
                    kh.getTenKH(),
                    kh.getSDT(),
                    kh.getDiaChi(),
                    kh.isGioiTinh() ? "Nam" : "Nữ",
                    kh.getNgaySinh(),
                    kh.getNgayTao(),
                    kh.getGhiChu(),
                    kh.getSoLanMua(),
                    icon
                };
                modelkh.addRow(row);
            }

        } catch (Exception e) {
            MessageService.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();

        }
    }

    public void timkiemTen() {
        DefaultTableModel modelkh = (DefaultTableModel) tblKhachHang.getModel();

        modelkh.setRowCount(0);
        try {
            String keyword = tkTen.getText();

            List<KhachHangModel> list = khser.selectByName(keyword);

            for (KhachHangModel kh : list) {
                Object[] row = {
                    kh.getMaKH(),
                    kh.getTenKH(),
                    kh.getSDT(),
                    kh.getDiaChi(),
                    kh.isGioiTinh() ? "Nam" : "Nữ",
                    kh.getNgaySinh(),
                    kh.getNgayTao(),
                    kh.getGhiChu(),
                    kh.getSoLanMua()};
                modelkh.addRow(row);
            }

        } catch (Exception e) {
            MessageService.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();

        }

    }

    public void timkiemTuoi() {
        try {
            DefaultTableModel modelkh = (DefaultTableModel) tblKhachHang.getModel();
            modelkh.setRowCount(0);
            String tktuoi1 = tkcboTuoi.getSelectedItem().toString();
            String tktuoi2 = tk2cboTuoi.getSelectedItem().toString();
            List<KhachHangModel> list = khser.selectByAge(tktuoi1, tktuoi2);

            for (KhachHangModel kh : list) {
                Object[] row = {
                    kh.getMaKH(),
                    kh.getTenKH(),
                    kh.getSDT(),
                    kh.getDiaChi(),
                    kh.isGioiTinh() ? "Nam" : "Nữ",
                    kh.getNgaySinh(),
                    kh.getNgayTao(),
                    kh.getGhiChu(),
                    kh.getSoLanMua()};
                modelkh.addRow(row);
            }

        } catch (Exception e) {
            MessageService.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();

        }
    }

    public void timkiemTen2() {
        DefaultTableModel modelkh = (DefaultTableModel) tblKhachHang2.getModel();

        modelkh.setRowCount(0);
        try {
            String keyword = tkTen.getText();

            List<KhachHangModel> list = khser.selectByName2(keyword);

            for (KhachHangModel kh : list) {
                Object[] row = {
                    kh.getMaKH(),
                    kh.getTenKH(),
                    kh.getSDT(),
                    kh.getDiaChi(),
                    kh.isGioiTinh() ? "Nam" : "Nữ",
                    kh.getNgaySinh(),
                    kh.getNgayTao(),
                    kh.getGhiChu(),
                    kh.getSoLanMua(), icon};
                modelkh.addRow(row);
            }

        } catch (Exception e) {
            MessageService.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();

        }

    }

    public void timkiemTuoi2() {
        try {
            DefaultTableModel modelkh = (DefaultTableModel) tblKhachHang2.getModel();
            modelkh.setRowCount(0);
            String tktuoi1 = tkcboTuoi.getSelectedItem().toString();
            String tktuoi2 = tk2cboTuoi.getSelectedItem().toString();
            List<KhachHangModel> list = khser.selectByAge2(tktuoi1, tktuoi2);

            for (KhachHangModel kh : list) {
                Object[] row = {
                    kh.getMaKH(),
                    kh.getTenKH(),
                    kh.getSDT(),
                    kh.getDiaChi(),
                    kh.isGioiTinh() ? "Nam" : "Nữ",
                    kh.getNgaySinh(),
                    kh.getNgayTao(),
                    kh.getGhiChu(),
                    kh.getSoLanMua(), icon};
                modelkh.addRow(row);
            }

        } catch (Exception e) {
            MessageService.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();

        }
    }

    @Override
    public void first() {

        this.row = 0;
        tblKhachHang.setRowSelectionInterval(row, row);
        this.edit();

    }

    @Override
    public void last() {
        this.row = tblKhachHang.getRowCount() - 1;
        tblKhachHang.setRowSelectionInterval(row, row);
        this.edit();
    }

    @Override
    public void next() {
        if (this.row < tblKhachHang.getRowCount() - 1) {
            this.row++;
            tblKhachHang.setRowSelectionInterval(row, row);
            this.edit();
        }
    }

    @Override
    public void previous() {
        if (this.row > 0) {
            this.row--;
            tblKhachHang.setRowSelectionInterval(row, row);
            this.edit();
        }
    }

    private void buttonintable() {
        Action delete = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (MessageService.confirm(rootPane, "Bạn muốn khôi phục khách hàng này không ?")) {
                    for (int row : tblKhachHang2.getSelectedRows()) {
                        int makh = (Integer) tblKhachHang2.getValueAt(row, 0);
                        khser.delete2(makh);
                    }
                    MessageService.alert(rootPane, "Khôi phục thành công");
                    fillTable2();
                    fillTable();
                }

            }

        };

        ButtonColumn buttonColumn = new ButtonColumn(tblKhachHang2, delete, 9);
        buttonColumn.setMnemonic(KeyEvent.VK_D);
    }

    private void setSize() {
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension d = t.getScreenSize();
        int h = d.height;
        int w = d.width;
        this.setSize(w, h);

    }

    private boolean chekrong() {

        if (txtHoTenKH2.getText().equals("")) {
            MessageService.alert(rootPane, "Không thể bỏ trống Họ tên");
            txtHoTenKH2.requestFocus();
            return false;
        } else if (txtSDT2.getText().equals("")) {
            MessageService.alert(rootPane, "Không thể bỏ trống  số điện thoại");
            txtSDT2.requestFocus();
            return false;
        } else if (txtDiaCHi2.getText().equals("")) {
            MessageService.alert(rootPane, "không thể bỏ trống địa chỉ");
            txtDiaCHi2.requestFocus();
            return false;
//        } else if () {
//            MessageService.alert(rootPane, "Không thể bỏ trống ngày sinh");
//            txtNgaySinh2.requestFocus();
//            return false;
//        } else if(ngaytao.length()==0){
//            MessageService.alert(rootPane, "không thể bỏ trống ngày tạo");
//            txtNgayTao2.requestFocus();
//            return false;
        } //        else if(txtGhiChu2.getText().equals("")){
        //            MessageService.alert(rootPane, "không thể bỏ trống ghi chú");
        //            txtGhiChu2.requestFocus();
        //            return false;
        //        }
        else if (this.txtNgaySinh2.getDate() == null) {
            MessageService.alert(rootPane, "Không để trống ngáy sinh!");
            txtNgaySinh2.requestFocus();
            return false;
        } else if (this.txtNgayTao2.getDate() == null) {
            MessageService.alert(rootPane, "Không để trống ngáy tạo!");
            txtNgaySinh2.requestFocus();
            return false;
        }

        return true;
    }

    private boolean checkvai() {

        if (!(txtSDT2.getText()).matches("[0-9]{10}")) {
            MessageService.alert(rootPane, "Số điện thoại phải nhập đúng 10 số");
            txtSDT2.requestFocus();
            return false;

        }
        return true;
    }

    @Override
    public boolean validateForm(boolean isEdit) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
