/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.Models.BusCPUModel;
import BUS.Models.BusCTSanPhamModel;
import BUS.Models.BusCameraModel;
import BUS.Models.BusDongSpModel;
import BUS.Models.BusHangModel;
import BUS.Models.BusHeDieuHanhModel;
import BUS.Models.BusManHinhModel;
import BUS.Models.BusMauSacModel;
import BUS.Models.BusPhanLoaiSpModel;
import BUS.Models.BusPinModel;
import BUS.Models.BusRamModel;
import BUS.Models.BusRomModel;
import BUS.Models.BusSanPham;
import BUS.Models.BusXuatXuModel;
import BUS.Services.BusImeiService;
import BUS.Services.BusPhanLoaiSpService;
import BUS.Services.CameraService;
import BUS.Services.CpuService;
import BUS.Services.DongSPService;
import BUS.Services.HangService;
import BUS.Services.HeDieuHanhService;
import BUS.Services.LoaiSPService;
import BUS.Services.ManHinhService;
import BUS.Services.MauSacService;
import BUS.Services.PinService;
import BUS.Services.RamService;
import BUS.Services.RomService;
import BUS.Services.SanPhamService;
import BUS.Services.XuatXuService;
import DAL.Models.DalCTSanPhamModel;
import DAL.Models.DalImeiModel;
import GUI.Services.IEditService;
import GUI.Services.ImageService;
import GUI.Services.MessageService;
import GUI.Services.UtilityService;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QuanLySanPham extends javax.swing.JInternalFrame implements IEditService<BusCTSanPhamModel> {

    public QuanLySanPham() {
        initComponents();
        this.init();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension d = t.getScreenSize();
        int h = d.height;
        int w = d.width;
        this.setSize(w, h);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel57 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        cboPin2 = new javax.swing.JComboBox<>();
        btnpin2 = new javax.swing.JButton();
        tabs = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel44 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        cboHang = new javax.swing.JComboBox<>();
        btnEditHang3 = new javax.swing.JButton();
        jPanel45 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        cboDongsp = new javax.swing.JComboBox<>();
        btnDong3 = new javax.swing.JButton();
        jPanel46 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        cboCamera = new javax.swing.JComboBox<>();
        btnCamera = new javax.swing.JButton();
        jPanel47 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        cboHeDieuHanh = new javax.swing.JComboBox<>();
        btnHeDieuHanh3 = new javax.swing.JButton();
        jPanel48 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        cboCpu = new javax.swing.JComboBox<>();
        btnCpu3 = new javax.swing.JButton();
        jPanel49 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        cboRom = new javax.swing.JComboBox<>();
        tbnRom3 = new javax.swing.JButton();
        jPanel50 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        cboRam = new javax.swing.JComboBox<>();
        btnRam3 = new javax.swing.JButton();
        jPanel51 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        cboManHinh = new javax.swing.JComboBox<>();
        btnManHinh3 = new javax.swing.JButton();
        jLabel70 = new javax.swing.JLabel();
        txtSearchBox = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        jPanel54 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        cboXuatXu = new javax.swing.JComboBox<>();
        btnXuatxu = new javax.swing.JButton();
        jPanel55 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        cboPin = new javax.swing.JComboBox<>();
        btnpin = new javax.swing.JButton();
        txtTonKho = new javax.swing.JTextField();
        cboSanPham = new javax.swing.JComboBox<>();
        btnLoaiSanPham = new javax.swing.JButton();
        jLabel69 = new javax.swing.JLabel();
        txtGiamDan = new javax.swing.JButton();
        btnTangDan = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        cboListImei = new javax.swing.JComboBox<>();
        btnOpenImei = new javax.swing.JButton();
        jLabel82 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        cboMauSac = new javax.swing.JComboBox<>();
        btnMauSac = new javax.swing.JButton();
        jPanel58 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        cboPhanLoai = new javax.swing.JComboBox<>();
        btnPhanLoai = new javax.swing.JButton();
        btnLamMoiForm = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecycle = new javax.swing.JTable();
        txtSearchRecycle = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        btnRestore = new javax.swing.JButton();

        jPanel57.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel84.setText("Pin");
        jPanel57.add(jLabel84);

        cboPin2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPin2ItemStateChanged(evt);
            }
        });
        jPanel57.add(cboPin2);

        btnpin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnpin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpin2ActionPerformed(evt);
            }
        });
        jPanel57.add(btnpin2);

        tabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsStateChanged(evt);
            }
        });

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sp", "Tên sp", "Loại", "Ram", "Pin", "Rom", "Màn Hình", "SL", "Tồn kho", "Giá sp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblSanPham);
        if (tblSanPham.getColumnModel().getColumnCount() > 0) {
            tblSanPham.getColumnModel().getColumn(0).setMinWidth(50);
            tblSanPham.getColumnModel().getColumn(0).setMaxWidth(50);
            tblSanPham.getColumnModel().getColumn(2).setMinWidth(80);
            tblSanPham.getColumnModel().getColumn(2).setMaxWidth(80);
            tblSanPham.getColumnModel().getColumn(3).setMinWidth(60);
            tblSanPham.getColumnModel().getColumn(3).setMaxWidth(60);
            tblSanPham.getColumnModel().getColumn(4).setMinWidth(60);
            tblSanPham.getColumnModel().getColumn(4).setMaxWidth(60);
            tblSanPham.getColumnModel().getColumn(5).setMinWidth(60);
            tblSanPham.getColumnModel().getColumn(5).setMaxWidth(60);
            tblSanPham.getColumnModel().getColumn(6).setMinWidth(60);
            tblSanPham.getColumnModel().getColumn(6).setMaxWidth(60);
            tblSanPham.getColumnModel().getColumn(7).setMinWidth(40);
            tblSanPham.getColumnModel().getColumn(7).setMaxWidth(40);
            tblSanPham.getColumnModel().getColumn(8).setMinWidth(50);
            tblSanPham.getColumnModel().getColumn(8).setMaxWidth(50);
            tblSanPham.getColumnModel().getColumn(9).setMinWidth(100);
            tblSanPham.getColumnModel().getColumn(9).setMaxWidth(100);
        }

        jPanel3.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 909, 410));

        jPanel44.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel61.setText("Hãng SP");
        jPanel44.add(jLabel61);

        cboHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboHangItemStateChanged(evt);
            }
        });
        jPanel44.add(cboHang);

        btnEditHang3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnEditHang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditHang3ActionPerformed(evt);
            }
        });
        jPanel44.add(btnEditHang3);

        jPanel3.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 500, 165, -1));

        jPanel45.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel62.setText("Dòng SP");
        jPanel45.add(jLabel62);

        cboDongsp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDongspItemStateChanged(evt);
            }
        });
        jPanel45.add(cboDongsp);

        btnDong3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnDong3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDong3ActionPerformed(evt);
            }
        });
        jPanel45.add(btnDong3);

        jPanel3.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 500, 170, -1));

        jPanel46.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel63.setText("Camera");
        jPanel46.add(jLabel63);

        jPanel46.add(cboCamera);

        btnCamera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCameraActionPerformed(evt);
            }
        });
        jPanel46.add(btnCamera);

        jPanel3.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 500, 167, -1));

        jPanel47.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel64.setText("Hệ điều hành");
        jPanel47.add(jLabel64);

        jPanel47.add(cboHeDieuHanh);

        btnHeDieuHanh3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnHeDieuHanh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeDieuHanh3ActionPerformed(evt);
            }
        });
        jPanel47.add(btnHeDieuHanh3);

        jPanel3.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 603, 157, -1));

        jPanel48.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel65.setText("CPU");
        jPanel48.add(jLabel65);

        jPanel48.add(cboCpu);

        btnCpu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnCpu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCpu3ActionPerformed(evt);
            }
        });
        jPanel48.add(btnCpu3);

        jPanel3.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 603, 165, -1));

        jPanel49.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel66.setText("Bộ nhớ trong");
        jPanel49.add(jLabel66);

        jPanel49.add(cboRom);

        tbnRom3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        tbnRom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnRom3ActionPerformed(evt);
            }
        });
        jPanel49.add(tbnRom3);

        jPanel3.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 169, -1));

        jPanel50.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel67.setText("Dung lượng RAM");
        jPanel50.add(jLabel67);

        jPanel50.add(cboRam);

        btnRam3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnRam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRam3ActionPerformed(evt);
            }
        });
        jPanel50.add(btnRam3);

        jPanel3.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 603, 169, -1));

        jPanel51.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel68.setText("Màn hình");
        jPanel51.add(jLabel68);

        jPanel51.add(cboManHinh);

        btnManHinh3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnManHinh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManHinh3ActionPerformed(evt);
            }
        });
        jPanel51.add(btnManHinh3);

        jPanel3.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 500, 157, -1));

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel70.setText("Tìm kiếm");
        jPanel3.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 14, 99, -1));

        txtSearchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchBoxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchBoxsearch(evt);
            }
        });
        jPanel3.add(txtSearchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 42, 426, 35));

        lblImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });
        jPanel3.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 232, 269));

        jPanel52.setLayout(new java.awt.GridLayout(1, 0, 3, 0));
        jPanel3.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 699, -1, 35));

        jPanel53.setLayout(new java.awt.GridLayout(1, 0, 3, 0));

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel53.add(btnFirst);

        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel53.add(btnBack);

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel53.add(btnNext);

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        jPanel53.add(btnLast);

        jPanel3.add(jPanel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 699, 230, 35));

        jLabel71.setText("Tên sản phẩm");
        jPanel3.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 294, -1, -1));

        txtMota.setColumns(20);
        txtMota.setRows(5);
        jScrollPane8.setViewportView(txtMota);

        jPanel3.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 530, 340, 70));

        jLabel72.setText("Mô tả");
        jPanel3.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 504, 40, -1));

        jLabel73.setText("Giá nhập");
        jPanel3.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 380, 55, -1));

        jLabel74.setText("Giá bán");
        jPanel3.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 380, 55, -1));

        jLabel75.setText("Tồn kho");
        jPanel3.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 440, 55, -1));

        jLabel77.setText("VNĐ");
        jPanel3.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(1231, 404, -1, -1));

        jLabel78.setText("VNĐ");
        jPanel3.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 403, -1, -1));

        txtGiaNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtGiaNhap.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(txtGiaNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, 130, 29));

        txtGiaBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtGiaBan.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(txtGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 400, 132, 31));

        jPanel54.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel79.setText("Xuất xứ");
        jPanel54.add(jLabel79);

        cboXuatXu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboXuatXuItemStateChanged(evt);
            }
        });
        jPanel54.add(cboXuatXu);

        btnXuatxu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnXuatxu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatxuActionPerformed(evt);
            }
        });
        jPanel54.add(btnXuatxu);

        jPanel3.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 603, 170, -1));

        jPanel55.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel80.setText("Pin");
        jPanel55.add(jLabel80);

        jPanel55.add(cboPin);

        btnpin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpinActionPerformed(evt);
            }
        });
        jPanel55.add(btnpin);

        jPanel3.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 603, 167, -1));

        txtTonKho.setEditable(false);
        txtTonKho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTonKho.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(txtTonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(1182, 461, 80, 33));

        jPanel3.add(cboSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 328, 298, 33));

        btnLoaiSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSanPhamActionPerformed(evt);
            }
        });
        jPanel3.add(btnLoaiSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 330, 37, 33));

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel69.setText("Sắp xếp theo");
        jPanel3.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 19, -1, -1));

        txtGiamDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sort.png"))); // NOI18N
        txtGiamDan.setText("Giá cao");
        txtGiamDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamDanActionPerformed(evt);
            }
        });
        jPanel3.add(txtGiamDan, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 42, -1, 35));

        btnTangDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tang.png"))); // NOI18N
        btnTangDan.setText("Giá thấp");
        btnTangDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangDanbtnTangDanActionPerformed(evt);
            }
        });
        jPanel3.add(btnTangDan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, -1, 35));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 699, 75, 35));

        jPanel3.add(cboListImei, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 461, 200, 33));

        btnOpenImei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnOpenImei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenImeiActionPerformed(evt);
            }
        });
        jPanel3.add(btnOpenImei, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 461, 37, 33));

        jLabel82.setText("Danh Sách Imei");
        jPanel3.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 443, 114, -1));

        jPanel56.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel83.setText("Màu sắc");
        jPanel56.add(jLabel83);

        jPanel56.add(cboMauSac);

        btnMauSac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMauSacActionPerformed(evt);
            }
        });
        jPanel56.add(btnMauSac);

        jPanel3.add(jPanel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 603, 167, -1));

        jPanel58.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        jLabel85.setText("Phân loại hàng");
        jPanel58.add(jLabel85);

        jPanel58.add(cboPhanLoai);

        btnPhanLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editing.png"))); // NOI18N
        btnPhanLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhanLoaiActionPerformed(evt);
            }
        });
        jPanel58.add(btnPhanLoai);

        jPanel3.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(1102, 603, 167, -1));

        btnLamMoiForm.setText("Làm mới");
        btnLamMoiForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiFormActionPerformed(evt);
            }
        });
        jPanel3.add(btnLamMoiForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1113, 699, -1, 35));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel3.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1032, 699, 75, 35));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 699, 75, 35));

        tabs.addTab("Sản phẩm", jPanel3);

        tblRecycle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sp", "Tên sp", "Hãng sp", "Dòng sp", "Xuất xứ", "CPU", "Ram", "Rom", "Màn hình", "Pin", "Camera", "Giá"
            }
        ));
        tblRecycle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRecycleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRecycle);

        txtSearchRecycle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchRecyclesearch(evt);
            }
        });

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel81.setText("Tìm kiếm");

        btnRestore.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Left.png"))); // NOI18N
        btnRestore.setText("Khôi phục lại");
        btnRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtSearchRecycle, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 712, Short.MAX_VALUE)
                .addComponent(btnRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel81)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchRecycle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRestore, txtSearchRecycle});

        tabs.addTab("Đã xóa", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchBoxsearch(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBoxsearch
        this.getDataTable();
    }//GEN-LAST:event_txtSearchBoxsearch

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        this.selectImage();
    }//GEN-LAST:event_lblImageMouseClicked

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        this.row = tblSanPham.getSelectedRow();
        this.edit();
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void cboHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboHangItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (cboHang.getSelectedIndex() >= 0) {
                QuanLySanPham.fillDongCombo();
            } else {
                QuanLySanPham.fillDongCombo();
                cboDongsp.getModel().setSelectedItem(new BusDongSpModel());
            }
        }
    }//GEN-LAST:event_cboHangItemStateChanged

    private void cboDongspItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDongspItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (cboDongsp.getSelectedIndex() >= 0) {
                QuanLySanPham.fillTenSanPhamCombo();
            } else {
                QuanLySanPham.fillTenSanPhamCombo();
                cboSanPham.getModel().setSelectedItem(new BusSanPham());
            }
        }
    }//GEN-LAST:event_cboDongspItemStateChanged

    private void cboXuatXuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboXuatXuItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {

        }
    }//GEN-LAST:event_cboXuatXuItemStateChanged

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiFormActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnLamMoiFormActionPerformed

    private void tbnRom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnRom3ActionPerformed
        new QLRom().setVisible(true);
    }//GEN-LAST:event_tbnRom3ActionPerformed

    private void btnManHinh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManHinh3ActionPerformed
        new QLManHinh().setVisible(true);
    }//GEN-LAST:event_btnManHinh3ActionPerformed

    private void btnEditHang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditHang3ActionPerformed
        new QLHangsp().setVisible(true);
    }//GEN-LAST:event_btnEditHang3ActionPerformed

    private void btnDong3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDong3ActionPerformed
        new QLDongSP().setVisible(true);
    }//GEN-LAST:event_btnDong3ActionPerformed

    private void btnCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCameraActionPerformed
        new QLCameraSp().setVisible(true);
    }//GEN-LAST:event_btnCameraActionPerformed

    private void btnCpu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCpu3ActionPerformed
        new QLCPU().setVisible(true);
    }//GEN-LAST:event_btnCpu3ActionPerformed

    private void btnXuatxuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatxuActionPerformed
        new QLXuatXu().setVisible(true);
    }//GEN-LAST:event_btnXuatxuActionPerformed

    private void btnpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpinActionPerformed
        new QLPin().setVisible(true);
    }//GEN-LAST:event_btnpinActionPerformed

    private void btnHeDieuHanh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeDieuHanh3ActionPerformed
        new QLHeDieuHanh().setVisible(true);
    }//GEN-LAST:event_btnHeDieuHanh3ActionPerformed

    private void btnRam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRam3ActionPerformed
        new QLRam().setVisible(true);
    }//GEN-LAST:event_btnRam3ActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        this.first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.previous();    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        this.next();    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        this.last();    }//GEN-LAST:event_btnLastActionPerformed

    private void btnLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSanPhamActionPerformed
        new QLLoaiSanPham().setVisible(true);
    }//GEN-LAST:event_btnLoaiSanPhamActionPerformed

    private void txtSearchRecyclesearch(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchRecyclesearch
        if(tabs.getSelectedIndex() == 0) {
            this.getDataTable();
        } else {
            this.getDataRecycle();
        }
    }//GEN-LAST:event_txtSearchRecyclesearch

    private void btnRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreActionPerformed
        if (this.rowRecycle >= 0) {
            this.backUp();
            btnRestore.setEnabled(false);
            this.rowRecycle = -1;
        } else {
            MessageService.alert(this, "Chọn dòng trên bảng");
        }
    }//GEN-LAST:event_btnRestoreActionPerformed

    private void tblRecycleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecycleMouseClicked
        this.rowRecycle = tblRecycle.getSelectedRow();
        this.currentIDRecycle = (int) tblRecycle.getValueAt(rowRecycle, 0);
        btnRestore.setEnabled(true);
    }//GEN-LAST:event_tblRecycleMouseClicked

    private void txtSearchBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBoxKeyPressed
    }//GEN-LAST:event_txtSearchBoxKeyPressed

    private void txtGiamDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamDanActionPerformed
        this.sortDesc();
    }//GEN-LAST:event_txtGiamDanActionPerformed

    private void btnTangDanbtnTangDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangDanbtnTangDanActionPerformed
        this.sortAsend();
    }//GEN-LAST:event_btnTangDanbtnTangDanActionPerformed

    private void tabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsStateChanged
        if(tabs.getSelectedIndex() == 0) {
            this.getDataTable();
        } else {
            this.getDataRecycle();
            this.clearForm();
            this.updateStatus();
        }
    }//GEN-LAST:event_tabsStateChanged

    private void btnOpenImeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenImeiActionPerformed
        if(this.row < 0) {
            new QLImei().setVisible(true);
        } else {
            int mactsp = (int) tblSanPham.getValueAt(row, 0);
            new QLImei(mactsp).setVisible(true);
        }
    }//GEN-LAST:event_btnOpenImeiActionPerformed

    private void btnMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMauSacActionPerformed
        new QLMauSac().setVisible(true);
    }//GEN-LAST:event_btnMauSacActionPerformed

    private void cboPin2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPin2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPin2ItemStateChanged

    private void btnpin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpin2ActionPerformed

    private void btnPhanLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanLoaiActionPerformed
        new QLPhanLoai().setVisible(true);
    }//GEN-LAST:event_btnPhanLoaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCamera;
    private javax.swing.JButton btnCpu3;
    private javax.swing.JButton btnDong3;
    private javax.swing.JButton btnEditHang3;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnHeDieuHanh3;
    private javax.swing.JButton btnLamMoiForm;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLoaiSanPham;
    private javax.swing.JButton btnManHinh3;
    private javax.swing.JButton btnMauSac;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnOpenImei;
    private javax.swing.JButton btnPhanLoai;
    private javax.swing.JButton btnRam3;
    private javax.swing.JButton btnRestore;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTangDan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatxu;
    private javax.swing.JButton btnpin;
    private javax.swing.JButton btnpin2;
    public static javax.swing.JComboBox<String> cboCamera;
    public static javax.swing.JComboBox<String> cboCpu;
    public static javax.swing.JComboBox<String> cboDongsp;
    public static javax.swing.JComboBox<String> cboHang;
    public static javax.swing.JComboBox<String> cboHeDieuHanh;
    public static javax.swing.JComboBox<String> cboListImei;
    public static javax.swing.JComboBox<String> cboManHinh;
    public static javax.swing.JComboBox<String> cboMauSac;
    public static javax.swing.JComboBox<String> cboPhanLoai;
    public static javax.swing.JComboBox<String> cboPin;
    public static javax.swing.JComboBox<String> cboPin2;
    public static javax.swing.JComboBox<String> cboRam;
    public static javax.swing.JComboBox<String> cboRom;
    public static javax.swing.JComboBox<String> cboSanPham;
    public static javax.swing.JComboBox<String> cboXuatXu;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblRecycle;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JButton tbnRom3;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JButton txtGiamDan;
    private javax.swing.JTextArea txtMota;
    private javax.swing.JTextField txtSearchBox;
    private javax.swing.JTextField txtSearchRecycle;
    public static javax.swing.JTextField txtTonKho;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel modelSp;
    DefaultTableModel modelRecycle;
    static DefaultComboBoxModel<BusCameraModel> cameraModel;
    static DefaultComboBoxModel<BusCPUModel> cpuModel;
    static DefaultComboBoxModel<BusDongSpModel> dongspModel;
    static DefaultComboBoxModel<BusHangModel> hangspModel;
    static DefaultComboBoxModel<BusHeDieuHanhModel> heDieuHanhModel;
    static DefaultComboBoxModel<BusManHinhModel> manHinhModel;
    static DefaultComboBoxModel<BusPinModel> pinModel;
    static DefaultComboBoxModel<BusRamModel> ramModel;
    static DefaultComboBoxModel<BusRomModel> romModel;
    static DefaultComboBoxModel<BusXuatXuModel> xuatXuModel;
    static DefaultComboBoxModel<BusSanPham> sanPhamModel;
    static DefaultComboBoxModel<BusMauSacModel> mauSacModel;
    static DefaultComboBoxModel<BusPhanLoaiSpModel> phanLoaiModel;
    static DefaultComboBoxModel<DalImeiModel> imeiModel;
    
    SanPhamService sanPhamService = new SanPhamService();
    LoaiSPService loaiSPService = new LoaiSPService();
    CameraService cameraService = new CameraService();
    CpuService cpuService = new CpuService();
    DongSPService dongSPService = new DongSPService();
    HangService hangService = new HangService();
    HeDieuHanhService heDieuHanhService = new HeDieuHanhService();
    ManHinhService manHinhService = new ManHinhService();
    PinService pinService = new PinService();
    RamService ramService = new RamService();
    RomService romService = new RomService();
    XuatXuService xuatXuService = new XuatXuService();
    int row = -1;

    List<BusCTSanPhamModel> listSp = new ArrayList<>();
    static List<BusDongSpModel> listDong = new ArrayList<>();
    static List<BusHangModel> listHang = new ArrayList<>();
    static List<BusCameraModel> listCamera = new ArrayList<>();
    static List<BusCPUModel> listCpu = new ArrayList<>();
    static List<BusHeDieuHanhModel> listHeDieuHanh = new ArrayList<>();
    static List<BusManHinhModel> listManHinh = new ArrayList<>();
    static List<BusPinModel> listPin = new ArrayList<>();
    static List<BusRamModel> listRam = new ArrayList<>();
    static List<BusRomModel> listRom = new ArrayList<>();
    static List<BusXuatXuModel> listXuatXu = new ArrayList<>();
    static List<BusSanPham> listLoaisp = new ArrayList<>();
    static List<BusPhanLoaiSpModel> listPhanLoai = new ArrayList<>();
    static List<BusMauSacModel> listMauSac = new ArrayList<>();
    static List<DalImeiModel> listImei = new ArrayList<>();

    @Override
    public void init() {
        this.setTitle("Quan ly sp");
        RomService.fillCombo(romModel, cboRom, listRom);
        CameraService.fillCombo(cameraModel, cboCamera, listCamera);
        CpuService.fillCombo(cpuModel, cboCpu, listCpu);
        HeDieuHanhService.fillCombo(heDieuHanhModel, cboHeDieuHanh, listHeDieuHanh);
        ManHinhService.fillCombo(manHinhModel, cboManHinh, listManHinh);
        PinService.fillCombo(pinModel, cboPin, listPin);
        RamService.fillCombo(ramModel, cboRam, listRam);
        XuatXuService.fillCombo(xuatXuModel, cboXuatXu, listXuatXu);
        QuanLySanPham.fillHangCombo();
        QuanLySanPham.fillTenSanPhamCombo();
        BusPhanLoaiSpService.fillCombo(phanLoaiModel, cboPhanLoai);
        MauSacService.fillCombo(mauSacModel, cboMauSac);
        
    }

    @Override
    public void setForm(BusCTSanPhamModel sp) {
        listImei.clear();
        if(sp.getMaCTSP() > 0) {
            BusImeiService.getImeiByMactsp(sp.getMaCTSP(), "");
            BusImeiService.fillComboImei(imeiModel, cboListImei, BusImeiService.listDalImei);
        }
        if (sp.getHinh() != null) {
            lblImage.setToolTipText(sp.getHinh());
            lblImage.setIcon(ImageService.readImage(sp.getHinh(), lblImage));
        } else {
            lblImage.setToolTipText(null);
            lblImage.setIcon(null);
        }
        txtTonKho.setText(sp.getTonKho() + "");
        txtGiaBan.setText(sp.getGiaBan() + "");
        txtGiaNhap.setText(sp.getGiaNhap() + "");
//        txtSoluongNhap.setText(sp.getSoLuongNhap() + "");
        txtMota.setText(sp.getMota());
        cboCamera.getModel().setSelectedItem(sp.getCameraModel());
        cboCpu.getModel().setSelectedItem(sp.getcPUModel());
        if (sp.getSanPhamModel() == null) {
            cboSanPham.getModel().setSelectedItem(sp.getSanPhamModel());
            cboDongsp.getModel().setSelectedItem(new BusDongSpModel());
            cboHang.getModel().setSelectedItem(new BusHangModel());
        } else {
            cboHang.getModel().setSelectedItem(sp.getSanPhamModel().getBusDongSpModel().getBusHangModel());
            cboDongsp.getModel().setSelectedItem(sp.getSanPhamModel().getBusDongSpModel());
            cboSanPham.getModel().setSelectedItem(sp.getSanPhamModel());
        }
        cboHeDieuHanh.getModel().setSelectedItem(sp.getHeDieuHanhModel());
        cboManHinh.getModel().setSelectedItem(sp.getManHinhModel());
        cboPin.getModel().setSelectedItem(sp.getPinModel());
        cboRam.getModel().setSelectedItem(sp.getRamModel());
        cboRom.getModel().setSelectedItem(sp.getRomModel());
        cboSanPham.getModel().setSelectedItem(sp.getSanPhamModel());
        cboXuatXu.getModel().setSelectedItem(sp.getXuatXuModel());
        if(sp.getBusMauSacModel() != null) {
            cboMauSac.getModel().setSelectedItem(sp.getBusMauSacModel());
        }else {
            cboMauSac.getModel().setSelectedItem(null);
        }
        if(sp.getBusPhanLoaiSpModel() != null) {
            cboPhanLoai.getModel().setSelectedItem(sp.getBusPhanLoaiSpModel());
        }else {
            cboPhanLoai.getModel().setSelectedItem(null);
        }
        cboListImei.getModel().setSelectedItem(new DalImeiModel());
    }

    @Override
    public void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblSanPham.getRowCount() - 1);

        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);

        btnFirst.setEnabled(edit && !first);
        btnLast.setEnabled(edit && !last);
        btnNext.setEnabled(edit && !last);
        btnBack.setEnabled(edit && !first);
    }

    public DalCTSanPhamModel getInfoForm() {
        DalCTSanPhamModel sp = new DalCTSanPhamModel();
        sp.setGiaBan(Float.parseFloat(txtGiaBan.getText()));
        sp.setGiaNhap(Float.parseFloat(txtGiaNhap.getText()));
        sp.setSoLuongNhap(listImei.size());
//        sp.setSoLuongNhap(Integer.parseInt(txtSoluongNhap.getText()));
        sp.setNgayNhap(new Date());
        sp.setTonKho(Integer.parseInt(txtTonKho.getText()));
        sp.setHinh(lblImage.getToolTipText());
        sp.setMota(txtMota.getText());

        BusCameraModel busCameraModel = (BusCameraModel) cboCamera.getSelectedItem();
        sp.setMaCamera(busCameraModel.getMaCamera());

        BusCPUModel busCPUModel = (BusCPUModel) cboCpu.getSelectedItem();
        sp.setMaSp(busCPUModel.getMaCPU());
        sp.setMaCpu(2);

        BusSanPham busSanPham = (BusSanPham) cboSanPham.getSelectedItem();
        sp.setMaSp(busSanPham.getMasp());

        BusHeDieuHanhModel busHeDieuHanhModel = (BusHeDieuHanhModel) cboHeDieuHanh.getSelectedItem();
        sp.setMaHeDieuHanh(Integer.parseInt(busHeDieuHanhModel.getMaHeDieuHanh()));

        BusManHinhModel busManHinhModel = (BusManHinhModel) cboManHinh.getSelectedItem();
        sp.setMaManHinh(Integer.parseInt(busManHinhModel.getMaManHinh()));

        BusRamModel busRamModel = (BusRamModel) cboRam.getSelectedItem();
        sp.setMaRam(busRamModel.getMaRam());

        BusPinModel busPinModel = (BusPinModel) cboPin.getSelectedItem();
        sp.setMaLoaiPin(Integer.parseInt(busPinModel.getMaLoaiPin()));

        BusRomModel busRomModel = (BusRomModel) cboRom.getSelectedItem();
        sp.setMaRom(busRomModel.getMaRom());

        BusXuatXuModel busXuatXuModel = (BusXuatXuModel) cboXuatXu.getSelectedItem();
        sp.setMaXuatXu(busXuatXuModel.getMaXuatXu());
        
        BusMauSacModel busMauSacModel = (BusMauSacModel) cboMauSac.getSelectedItem();
        sp.setMaMau(busMauSacModel.getDalMauSacModel().getMaMau());
        
        BusPhanLoaiSpModel phanLoaiSpModel = (BusPhanLoaiSpModel) cboPhanLoai.getSelectedItem();
        sp.setMaPhanLoai(phanLoaiSpModel.getDalPhanLoaiSpModel().getMaPhanLoai());

        return sp;
    }

    @Override
    public void insert() {
        DalCTSanPhamModel sp = this.getInfoForm();
        try {
            sanPhamService.insert(sp);
            int lastId = sanPhamService.selectLastIdSp();
            listImei.forEach(dalImeiModel -> {
                dalImeiModel.setMaCtsp(lastId);
                BusImeiService.insert(dalImeiModel);
            });
            this.clearForm();
            this.getDataTable();
            MessageService.alert(this, "yeahhhh");
        } catch (Exception e) {
            MessageService.alert(this, "error");
        }
    }
    @Override
    public void update() {
        int mactsp = (int) tblSanPham.getValueAt(row, 0);
        DalCTSanPhamModel sp = this.getInfoForm();
        sp.setMactsp(mactsp);
        try {
            sanPhamService.update(sp);
            listImei.forEach(dalImeiModel -> {
                BusImeiService.update(dalImeiModel);
            });
            this.getDataTable();
            MessageService.alert(this, "yeahhhh");
        } catch (Exception e) {
            MessageService.alert(this, "error");
        }
    }

    @Override
    public void delete() {
        int id = (int) tblSanPham.getValueAt(row, 0);
        try {
            sanPhamService.delete(id);
            this.clearForm();
            this.getDataTable();
            MessageService.alert(this, "yeahhhh");
        } catch (Exception e) {
            MessageService.alert(this, "error");
        }
    }

    @Override
    public void edit() {
        int id = (int) tblSanPham.getValueAt(this.row, 0);
        try {
            BusCTSanPhamModel sp = sanPhamService.selectID(id);
            this.setForm(sp);
            this.updateStatus();
        } catch (Exception e) {
        }
    }

    @Override
    public void clearForm() {
        this.row = -1;
        BusCTSanPhamModel sp = new BusCTSanPhamModel();
        this.setForm(sp);
        this.updateStatus();
    }

    int rowRecycle = -1;
    int currentIDRecycle;

    void backUp() {
        try {
            sanPhamService.backup(currentIDRecycle);
            this.clearForm();
            this.getDataRecycle();
            MessageService.alert(this, "yeahhhh");
        } catch (Exception e) {
            MessageService.alert(this, "error");
        }
    }

    void getDataTable() {
        String keyWord = txtSearchBox.getText();
        try {
            this.listSp = sanPhamService.selectBySearch(0,keyWord);
            fillTableSP(listSp, modelSp, tblSanPham);
        } catch (Exception e) {
            MessageService.alert(this, "loi");
        }
    }
    void getDataRecycle() {
        String keyWord = txtSearchRecycle.getText();
        try {
            this.listSp = sanPhamService.selectRecycle(0,keyWord);
            fillTableSP(listSp, modelRecycle, tblRecycle);
        } catch (Exception e) {
            MessageService.alert(this, "loi");
        }
    }

    void fillTableSP(List<BusCTSanPhamModel> list, DefaultTableModel model, JTable tbl) {
        model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        for(BusCTSanPhamModel sp : list) {
            model.addRow(new Object[]{
                sp.getMaCTSP(),
                sp.getSanPhamModel().getTensp(),
                sp.getBusPhanLoaiSpModel().getDalPhanLoaiSpModel().getTenLoai(),
                sp.getRamModel().getDungLuongRam() + " gb",
                sp.getPinModel().getDungLuongPin() + " mAh",
                sp.getRomModel().getDungLuongRom() + " gb",
                sp.getManHinhModel().getKichThuoc() + " inch",
                sp.getSoLuongNhap(),
                sp.getTonKho(),
                UtilityService.toVnd(sp.getGiaBan())
            });
        };
        this.row = -1;
        this.rowRecycle = -1;
        btnRestore.setEnabled(false);
    }
    void selectImage() {
        try {
            JFileChooser fileChooser = new JFileChooser("image\\");
            int kq = fileChooser.showOpenDialog(fileChooser);
            if (kq == JFileChooser.APPROVE_OPTION) {
                File file = fileChooser.getSelectedFile();
                ImageService.save(file);
                ImageIcon icon = ImageService.readImage(file.getName(), lblImage);
                lblImage.setIcon(icon);
                lblImage.setToolTipText(file.getName());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn ảnh...");
            }

        } catch (Exception a) {

        }

    }
    Comparator<BusCTSanPhamModel> comparator = Comparator.comparing(BusCTSanPhamModel::getGiaBan);

    void sortDesc() {
        Collections.sort(listSp, comparator);
        Collections.reverse(listSp);
        fillTableSP(listSp, modelSp, tblSanPham);
    }

    void fill() {
        modelSp = (DefaultTableModel) tblSanPham.getModel();
        modelSp.setRowCount(0);
        this.clearForm();
        if (this.listSp.size() > 0) {
            this.listSp.forEach(sp -> {
                this.modelSp.addRow(new Object[]{
                    sp.getMaCTSP(),
                    sp.getSanPhamModel().getTensp(),
                    UtilityService.toVnd(sp.getGiaBan()),
                    sp.getRamModel().getDungLuongRam() + " gb",
                    sp.getPinModel().getDungLuongPin() + " mnAh",
                    sp.getcPUModel().getTenCPU(),
                    sp.getRomModel().getDungLuongRom() + " gb",
                    sp.getManHinhModel().getKichThuoc() + " inch",
                    sp.getTonKho()
                });
            });
        }
    }


    static void fillTenSanPhamCombo() {
        LoaiSPService loaiSPService = new LoaiSPService();
        QuanLySanPham.sanPhamModel = (DefaultComboBoxModel) cboSanPham.getModel();
        QuanLySanPham.sanPhamModel.removeAllElements();
        BusDongSpModel busDongSpModel = (BusDongSpModel) cboDongsp.getSelectedItem();
        try {
            if (busDongSpModel != null) {
                QuanLySanPham.listLoaisp = loaiSPService.selectByDongsp(busDongSpModel.getMaDong());
            }

            if (QuanLySanPham.listLoaisp != null) {
                QuanLySanPham.listLoaisp.forEach(sp -> {
                    QuanLySanPham.sanPhamModel.addElement(sp);
                });
            }
            cboSanPham.getModel().setSelectedItem(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static void fillDongCombo() {
        DongSPService dongSPService = new DongSPService();
        QuanLySanPham.dongspModel = (DefaultComboBoxModel) cboDongsp.getModel();
        QuanLySanPham.dongspModel.removeAllElements();
        BusHangModel busHangModel = (BusHangModel) cboHang.getSelectedItem();
        try {
            if (busHangModel != null) {
                QuanLySanPham.listDong = dongSPService.selectByHangsp(busHangModel.getMaHang());
                if (QuanLySanPham.listDong != null) {
                    QuanLySanPham.listDong.forEach(dong -> {
                        QuanLySanPham.dongspModel.addElement(dong);
                    });
                }
                cboDongsp.getModel().setSelectedItem(null);
                QuanLySanPham.fillTenSanPhamCombo();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static void fillHangCombo() {
        HangService hangService = new HangService();
        QuanLySanPham.hangspModel = (DefaultComboBoxModel) cboHang.getModel();
        QuanLySanPham.hangspModel.removeAllElements();
        try {
            QuanLySanPham.listHang = hangService.selectAll();
            if (QuanLySanPham.listHang != null) {
                QuanLySanPham.listHang.forEach(hang -> {
                    QuanLySanPham.hangspModel.addElement(hang);
                });
                cboHang.getModel().setSelectedItem(null);
                QuanLySanPham.fillDongCombo();
            }
        } catch (Exception e) {
        }
    }

    void sortAsend() {
        Collections.sort(listSp, comparator);
        fillTableSP(listSp, modelSp, tblSanPham);
    }

    @Override
    public void first() {
        this.row = 0;
        tblSanPham.setRowSelectionInterval(row, row);
        this.edit();
    }

    @Override
    public void last() {
        this.row = tblSanPham.getRowCount() - 1;
        tblSanPham.setRowSelectionInterval(row, row);
        this.edit();
    }

    @Override
    public void next() {
        if (this.row < tblSanPham.getRowCount() - 1) {
            this.row++;
            tblSanPham.setRowSelectionInterval(row, row);
            this.edit();
        }
    }

    @Override
    public void previous() {
        if (this.row > 0) {
            this.row--;
            tblSanPham.setRowSelectionInterval(row, row);
            this.edit();
        }
    }

    @Override
    public boolean validateForm(boolean isEdit) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public BusCTSanPhamModel getForm() {
        return null;
    }

    @Override
    public void fillTable() {

    }
}
