/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.Models.BusCTSanPhamModel;
import BUS.Models.BusSanPham;
import BUS.Services.SanPhamService;
import GUI.Services.ImageService;
import GUI.Services.UtilityService;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class XemChiTietSanPham extends javax.swing.JFrame {

    /**
     * Creates new form XemChiTietSanPham
     */
    int id;

    public XemChiTietSanPham(int id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.id = id;
        desginTable();
        this.init();
    }
public void desginTable() {
        tblThuocTinh.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        tblThuocTinh.getTableHeader().setOpaque(false);
        tblThuocTinh.getTableHeader().setBackground(new Color(25, 29, 74));
       tblThuocTinh.getTableHeader().setForeground(Color.WHITE);
        
//        tblThuocTinh.getTableHeader().setDraggedColumn(null);
//        tblNKD.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
//      tblNKD.getTableHeader().setOpaque(false);
//         tblNKD.getTableHeader().setBackground(new Color(25, 29, 74));
//         tblNKD.getTableHeader().setForeground(Color.WHITE);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblGia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThuocTinh = new javax.swing.JTable();
        lblTenSanPham = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm\n"));

        lblGia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGia.setForeground(new java.awt.Color(204, 0, 0));
        lblGia.setText("Giá sản phẩm");

        tblThuocTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblThuocTinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Hãng sản phẩm", null},
                {"Dòng sản phẩm", null},
                {"CPU", null},
                {"Ram", null},
                {"Bộ nhớ trong", null},
                {"Màn hình", null},
                {"Cameta", null},
                {"Xuất xứ", null},
                {"Pin", null},
                {"Hệ điều hành", null}
            },
            new String [] {
                "Thông tin", "Thuộc tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThuocTinh.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblThuocTinh.setRowHeight(30);
        tblThuocTinh.setShowGrid(true);
        jScrollPane1.setViewportView(tblThuocTinh);
        if (tblThuocTinh.getColumnModel().getColumnCount() > 0) {
            tblThuocTinh.getColumnModel().getColumn(0).setMinWidth(140);
            tblThuocTinh.getColumnModel().getColumn(0).setMaxWidth(140);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblGia)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
        );

        lblTenSanPham.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTenSanPham.setText("Tên sản phẩm");

        lblImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTenSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTenSanPham)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(XemChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(XemChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(XemChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(XemChiTietSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new XemChiTietSanPham().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblTenSanPham;
    private javax.swing.JTable tblThuocTinh;
    // End of variables declaration//GEN-END:variables
    BusCTSanPhamModel sp = new BusCTSanPhamModel();
    SanPhamService sanPhamService = new SanPhamService();
    DefaultTableModel model;

    void init() {
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        sp = sanPhamService.selectID(id);
        this.fillToTable();
    }

    void fillToTable() {
        if (sp.getHinh() != null) {
            lblImage.setToolTipText(sp.getHinh());
            lblImage.setIcon(ImageService.readImage(sp.getHinh(), lblImage));
        } else {
            lblImage.setToolTipText(null);
            lblImage.setIcon(null);
        }
        
        lblGia.setText(UtilityService.toVnd(sp.getGiaBan()));
        lblTenSanPham.setText(sp.getSanPhamModel().getTensp());
        model = (DefaultTableModel) tblThuocTinh.getModel();
        model.setRowCount(0);
        String thuocTinh[] = {"Màu sắc", "Phân loại","Hãng sản phẩm", "Dòng sản phẩm", "CPU", "Ram", "Bộ nhớ trong", "Màn hình", "Camera", "Xuất xứ", "Pin", "Hệ điều hành"};
        String thongTin[] = {
            sp.getBusMauSacModel().getDalMauSacModel().getTenMau(),
            sp.getBusPhanLoaiSpModel().getDalPhanLoaiSpModel().getTenLoai(),
            sp.getSanPhamModel().getBusDongSpModel().getBusHangModel().getTenHang(),
            sp.getSanPhamModel().getBusDongSpModel().getTenDong(),
            sp.getcPUModel().getTenCPU(),
            sp.getRamModel().getLoaiRam() + ", " + sp.getRamModel().getDungLuongRam() + " Gb",
            sp.getRomModel().getLoaiRon() + ", " + sp.getRomModel().getDungLuongRom() + " Gb",
            sp.getManHinhModel().getLoaiManHinh() + ", " + sp.getManHinhModel().getDoPhanGiaiManHinh(),
            sp.getCameraModel().getTenCamera() + ", " + sp.getCameraModel().getDoPhanGiai(),
            sp.getXuatXuModel().getNoiXuatXu(),
            sp.getPinModel().getLoaiPin() + ", " + sp.getPinModel().getDungLuongPin() + " mAh",
            sp.getHeDieuHanhModel().getTenHeDieuHanh()
        };
        for(int i = 0; i < thongTin.length; i++) {
            model.addRow(new Object[] {
                thuocTinh[i],
                thongTin[i]
            });
        }
    }
}
